#!/bin/bash
# main.sh - the entrypoint logic: the global-option table, dispatch, help,
# and the signal/EXIT traps. bin/sciebo is reduced to the Bash-version guard
# and `source lib/sciebo.sh; sciebo_main "$@"`; everything below only
# defines functions and tables, so sourcing this file (lib/sciebo.sh's job)
# has no side effect beyond that - all real work happens inside sciebo_main.

# Global options are described once, in _SCIEBO_GLOBAL_SPECS (generated by
# scripts/gen-cli.sh from lib/cli/sciebo.spec into lib/cli/registry.sh,
# sourced before this file - see lib/sciebo.sh), and consumed by
# _sciebo_consume_globals. Each record is
#   <flag>[,<alias>...]|<env-var>|<kind>|<early>
# where kind is:
#   value    consume the next argument, or the --flag=VALUE form
#   flag     set ENV_VAR=1 and take no argument
#   version  print the version and exit
# early=1 marks an option that must be consumed before settings_init_paths
# derives the config/state layout: --confdir/--log-dir/--log-expire are
# exported by the early pass in sciebo_main and never reach a command parser
# (global options may appear anywhere).

# _SCIEBO_GLOBAL_BY_FLAG maps every flag and alias to "<env>|<kind>|<early>".
# It is built once here so the argument walk below is a single associative
# lookup instead of re-splitting every spec on every iteration.
declare -gA _SCIEBO_GLOBAL_BY_FLAG=()
for _sciebo_spec in "${_SCIEBO_GLOBAL_SPECS[@]}"; do
  IFS='|' read -r _sciebo_flags_csv _sciebo_env _sciebo_kind _sciebo_early <<<"$_sciebo_spec"
  IFS=',' read -r -a _sciebo_names <<<"$_sciebo_flags_csv"
  for _sciebo_flag in "${_sciebo_names[@]}"; do
    _SCIEBO_GLOBAL_BY_FLAG["$_sciebo_flag"]="$_sciebo_env|$_sciebo_kind|$_sciebo_early"
  done
done
unset _sciebo_spec _sciebo_flags_csv _sciebo_env _sciebo_kind _sciebo_early _sciebo_names _sciebo_flag

# _sciebo_classify_arg ARG - split ARG into its flag and value halves for the
# global walkers: sets _SCIEBO_ARG_FLAG to the text before the first '=' (ARG
# itself when there is none) and _SCIEBO_ARG_HAS_VALUE to 1 when the =value
# form was used. Writes globals instead of printing so each walker reads the
# result without a command-substitution fork.
_sciebo_classify_arg() {
  _SCIEBO_ARG_FLAG="${1:-}"
  _SCIEBO_ARG_HAS_VALUE=0
  case "$_SCIEBO_ARG_FLAG" in
    *=*)
      _SCIEBO_ARG_HAS_VALUE=1
      _SCIEBO_ARG_FLAG="${_SCIEBO_ARG_FLAG%%=*}"
      ;;
  esac
  return 0
}

# _sciebo_consume_globals NAME MODE TARGET ARGS... - walk ARGS and consume the
# globals in _SCIEBO_GLOBAL_BY_FLAG. MODE "early" consumes only the early=1
# options; MODE "all" consumes every one. Unconsumed arguments are appended,
# in order, to the array named by TARGET. NAME labels value errors.
_sciebo_consume_globals() {
  local name="$1" mode="$2" target="$3"
  shift 3
  local -n _out="$target"
  local arg="" flag="" value="" entry="" env="" kind="" early=""
  local has_value=0
  _out=()
  while [[ $# -gt 0 ]]; do
    arg="$1"
    value=""
    _sciebo_classify_arg "$arg"
    flag="$_SCIEBO_ARG_FLAG"
    has_value=$_SCIEBO_ARG_HAS_VALUE
    if [[ "$has_value" -eq 1 ]]; then
      value="${arg#*=}"
    fi
    entry="${_SCIEBO_GLOBAL_BY_FLAG[$flag]:-}"
    if [[ -z "$entry" ]]; then
      _out[${#_out[@]}]="$arg"
      shift
      continue
    fi
    IFS='|' read -r env kind early <<<"$entry"
    if [[ "$mode" == "early" && "$early" != "1" ]]; then
      _out[${#_out[@]}]="$arg"
      shift
      continue
    fi
    # Only value-kind options accept the --flag=value form; for flag/version
    # kinds it is an unmatched argument, exactly as before.
    if [[ "$has_value" -eq 1 && "$kind" != "value" ]]; then
      _out[${#_out[@]}]="$arg"
      shift
      continue
    fi
    case "$kind" in
      version)
        printf '%s %s\n' "$name" "${SCIEBO_VERSION:-unknown}"
        exit 0
        ;;
      flag)
        declare -gx "$env=1"
        ;;
      value)
        if [[ "$has_value" -eq 1 ]]; then
          declare -gx "$env=$value"
        else
          if [[ -z "${2:-}" ]]; then
            printf '%s: %s requires a value\n' "$name" "$flag" >&2
            exit 2
          fi
          declare -gx "$env=$2"
          shift
        fi
        ;;
    esac
    shift
  done
}

# SCIEBO_COMMANDS (generated by scripts/gen-cli.sh from lib/cli/sciebo.spec
# into lib/cli/registry.sh, sourced before this file) is the single source
# of truth for dispatch and the help listing. Command modules themselves
# stay lazy: an invocation only parses the dispatched command's module
# instead of the whole lib/commands tree.

# is_command NAME - true when NAME is one of the SCIEBO_COMMANDS entries.
# The dispatch and the help lookup share this list, so they cannot drift
# apart.
is_command() {
  case " $SCIEBO_COMMANDS " in
    *" $1 "*) return 0 ;;
  esac
  return 1
}

usage_main() {
  usage_emit <<'EOF'
Usage: sciebo <command> [options]

Sync local directories with a sciebo (Nextcloud/WebDAV) remote via rclone.
Transfers and deletions happen only through `sync` and `cleanup --apply`.

Commands:
  setup                     create/update the sciebo rclone remote
  doctor [--offline]        preflight checks (PASS/WARN/FAIL report)
  discover [--write]        find git repositories under roots.conf
  list                      list configured sources (mode, name, paths, filter)
  check                     dry run of all sources (no changes)
  sync [options]            apply sync/pull/bisync for all sources
  verify [options]          check that sources match their destinations
  status [options]          last run per source, plus the pause state
  pause [--for DURATION]    skip sync/check runs until resumed
  resume                    clear the pause marker
  folders <subcommand>      choose/add/list/remove folder pairs
  mount [options]           mount the remote on demand (nfsmount)
  umount <selector>         unmount a recorded mount
  mounts [--folder SUB]     show recorded mounts
  cleanup [options]         old logs / stale chunk-upload housekeeping
  schedule <subcommand>     install/uninstall/status of the launchd agent
  trash [subcommand]        list/restore/remove/empty the Nextcloud trashbin
  versions SUB [options]    list/download/restore/delete file versions
  share <subcommand>        create, list, update, or remove Nextcloud shares
  lock SUB / unlock SUB     lock or unlock a remote file (WebDAV)
  locks [options]           list locks recorded by `sciebo lock`
  quota                     show server quota usage
  open [SUB]                open a local sync folder (--web opens the browser)
  conflicts [options]       find or resolve local conflict copies
  retry [NAME [PATH]]       clear failure-blacklist entries
  account <subcommand>      manage profiles (list/add/remove/use/info/avatar)
  logout [--yes]            remove credentials for the active remote
  config <subcommand>       show effective settings and their source
  support [options]         build a redacted debug archive
  nextcloudcmd [options]    nextcloudcmd-compatible single sync run
  watch [options]           run sync when local files change
  limit / unlimited         cap or lift bandwidth for later runs
  network [--json]          show the active network and metered state
  filters <subcommand>      manage filter files (sync fetches the server list)
  hydrate SUB               download a remote path on demand
  provision [options]       non-interactive account and folder setup
  logs [subcommand]         list, show, or tail per-source sync logs
  ignored [SUB]             list files excluded from syncing
  download SUB [DEST]       download a remote file or directory
  update [--check]          update the local checkout from git

Extra commands (Nextcloud server features; covered by the isolated test
suite but not by the real-server contract suite):
  notifications             list or delete Nextcloud notifications
  activity                  show the Nextcloud activity stream
  presence [set ...]        show or set your Nextcloud user status
  file <subcommand>         file details, activity, and shares
  search TERM [options]     unified search on the server
  recent [options]          recently modified remote files
  comments <subcommand>     file comments (Nextcloud comments app)
  favorites [options]       list or toggle server-side favorites
  tags <subcommand>         list system tags and assign them
  server <subcommand>       server information and capabilities
  edit SUB [options]        download, edit, and upload one remote file
  announcements [options]   list server announcements
  preview SUB [options]     download a preview image for a remote file

Global options (before the command): --profile NAME, --trust,
--non-interactive, --debug, --log-file FILE, --log-dir DIR,
--log-expire HOURS, --confdir DIR, --version.

Run `sciebo help <command>` or `<command> --help` for command options.
EOF
}

# Global options that may precede any command. They are extracted before
# dispatch and exported as settings; command parsers never see them.
GLOBAL_ARGS=()

# extract_global_flags "$@" - pull global options out of the command line and
# leave the remaining arguments in GLOBAL_ARGS. _SCIEBO_GLOBAL_SPECS is the
# single source of truth; the early scan already consumed the path-affecting
# ones, but they are accepted here too so direct callers keep working.
extract_global_flags() {
  _sciebo_consume_globals "$CLI_NAME" all GLOBAL_ARGS "$@"
}

# main COMMAND ARGS... - dispatch an already-resolved command. The global
# options are consumed and the command module is sourced (at global scope)
# before this runs, so it only routes to cmd_/usage_.
main() {
  local command="${1:-help}"
  [[ $# -eq 0 ]] || shift
  case "$command" in
    help | -h | --help)
      if [[ $# -eq 0 ]]; then
        usage_main
      elif is_command "$1"; then
        "usage_$1"
      else
        printf '%s: unknown command: %s\n\n' "$CLI_NAME" "$1" >&2
        usage_main >&2
        exit 2
      fi
      ;;
    *)
      if is_command "$command"; then
        "cmd_${command}" "$@"
      else
        printf '%s: unknown command: %s\n\n' "$CLI_NAME" "$command" >&2
        usage_main >&2
        exit 2
      fi
      ;;
  esac
}

# _sciebo_on_signal SIGNAL - INT/TERM handler: release the run lock and
# exit with the conventional 128+SIGNAL status (130 for INT, 143 for TERM)
# so `kill` on the sciebo pid surfaces the signal instead of a clean 0.
# release_lock is idempotent (a no-op when nothing was ever acquired, and
# harmless if the EXIT trap runs again after it).
_sciebo_on_signal() {
  local status=130
  [[ "$1" != "TERM" ]] || status=143
  release_lock || true
  exit "$status"
}

# _sciebo_on_exit - release the run lock (see _sciebo_on_signal) and remove
# any registered temp file (the curl netrc that carries the app password,
# response bodies).
_sciebo_on_exit() {
  release_lock || true
  sciebo_temp_cleanup || true
}

# sciebo_main ARGS... - the process entrypoint, called by bin/sciebo right
# after lib/sciebo.sh has eagerly loaded every rank 1-6 library. Installs the
# signal/EXIT traps, consumes the global options (the early pass, then the
# full pass - both modes preserve edge semantics like `--profile --confdir
# X`), derives the config/state layout, sources the dispatched command
# module at global scope, and dispatches.
sciebo_main() {
  trap '_sciebo_on_signal INT' INT
  trap '_sciebo_on_signal TERM' TERM
  trap _sciebo_on_exit EXIT

  # Early scan: the path-affecting globals must be exported before
  # settings_init_paths derives the config/state layout below.
  local -a _sciebo_early=()
  _sciebo_consume_globals "sciebo" early _sciebo_early "$@"
  if [[ "${#_sciebo_early[@]}" -gt 0 ]]; then
    set -- "${_sciebo_early[@]}"
  else
    set --
  fi

  # Resolve the global options and the dispatched command, then source the
  # command module at global scope: sourcing inside a function would scope
  # the module's top-level `declare -A`/`declare -g` declarations to that
  # function and drop them when it returns - sciebo_main itself is a
  # function, so every command module's top-level declarations must (and
  # do; scripts/check-layers.sh enforces it) use -g. --version/-V is
  # consumed by extract_global_flags and exits before any command module is
  # read.
  extract_global_flags "$@"
  if [[ "${#GLOBAL_ARGS[@]}" -gt 0 ]]; then
    set -- "${GLOBAL_ARGS[@]}"
  else
    set --
  fi
  local _sciebo_command="${1:-help}"
  [[ $# -eq 0 ]] || shift

  # Both global-option passes are done (early above, all just now): derive
  # the config/state layout before any command module is sourced, including
  # the `help <command>` path, which needs no module but must see the same
  # layout a real dispatch would.
  settings_init_paths

  # _sciebo_dispatch_target is the command whose module must be sourced:
  # $1 for `help <command>`/`<command> --help`, or the dispatched command
  # itself. Empty for a bare `help` (usage_main needs no module).
  local _sciebo_dispatch_target=""
  if [[ "$_sciebo_command" == "help" || "$_sciebo_command" == "-h" || "$_sciebo_command" == "--help" ]]; then
    if [[ $# -gt 0 ]] && is_command "$1"; then
      _sciebo_dispatch_target="$1"
    fi
  elif is_command "$_sciebo_command"; then
    _sciebo_dispatch_target="$_sciebo_command"
  fi
  if [[ -n "$_sciebo_dispatch_target" ]]; then
    # Bash 5.3 forkless command substitution: no subshell per dispatch;
    # sciebo_command_module keeps its print-to-stdout contract (a `die`
    # inside it exits the script just as the old failing assignment did
    # under `set -e`). No command module ever calls into another, so this
    # is the only lib/commands/ file the dispatch needs.
    # shellcheck source=/dev/null  # runtime path relative to LIB_DIR
    source "${ sciebo_command_module "$_sciebo_dispatch_target";}" # layers: allow-source (lazy lib/commands/ dispatch, not library code)
  fi

  main "$_sciebo_command" "$@"
}
