#!/bin/bash
# Generated by scripts/gen-cli.sh from lib/cli/sciebo.spec; do not edit.
#
# The runtime CLI registry: the command list, the command-to-module map, the
# tier map, and the global-option table - lib/sciebo.sh and lib/cli/main.sh
# source this file (the cli layer, before lib/cli/main.sh itself). Data
# only, no functions: see lib/cli/sciebo.spec for what each table means and
# lib/cli/main.sh/lib/sciebo.sh for how they are consumed.

# shellcheck disable=SC2034  # read by lib/cli/main.sh's is_command
SCIEBO_COMMANDS="setup doctor discover list check sync verify status pause resume folders mount umount mounts cleanup schedule trash versions share notifications activity presence lock unlock locks quota open conflicts retry account logout config support nextcloudcmd watch limit unlimited network filters file search recent comments favorites tags server hydrate provision logs edit ignored announcements preview download update"

# shellcheck disable=SC2034  # read by lib/sciebo.sh's sciebo_command_module
declare -gA SCIEBO_COMMAND_MODULE=(
  [setup]=setup
  [doctor]=doctor
  [discover]=discover
  [list]=list
  [check]=sync
  [sync]=sync
  [verify]=verify
  [status]=status
  [pause]=pause
  [resume]=pause
  [folders]=folders
  [mount]=mount
  [umount]=mount
  [mounts]=mount
  [cleanup]=cleanup
  [schedule]=schedule
  [trash]=trash
  [versions]=versions
  [share]=share
  [notifications]=notifications
  [activity]=activity
  [presence]=presence
  [lock]=lock
  [unlock]=lock
  [locks]=lock
  [quota]=quota
  [open]=open
  [conflicts]=conflicts
  [retry]=retry
  [account]=account
  [logout]=logout
  [config]=config
  [support]=support
  [nextcloudcmd]=nextcloudcmd
  [watch]=watch
  [limit]=limit
  [unlimited]=limit
  [network]=network
  [filters]=filters
  [file]=file
  [search]=search
  [recent]=recent
  [comments]=comments
  [favorites]=favorites
  [tags]=tags
  [server]=server
  [hydrate]=hydrate
  [provision]=provision
  [logs]=logs
  [edit]=edit
  [ignored]=ignored
  [announcements]=announcements
  [preview]=preview
  [download]=download
  [update]=update
)

# shellcheck disable=SC2034  # part of the generated registry; not read by the runtime dispatch today, kept for tooling that needs the core/extra split without re-deriving it from the spec
declare -gA SCIEBO_COMMAND_TIER=(
  [setup]=core
  [doctor]=core
  [discover]=core
  [list]=core
  [check]=core
  [sync]=core
  [verify]=core
  [status]=core
  [pause]=core
  [resume]=core
  [folders]=core
  [mount]=core
  [umount]=core
  [mounts]=core
  [cleanup]=core
  [schedule]=core
  [trash]=core
  [versions]=core
  [share]=core
  [notifications]=extra
  [activity]=extra
  [presence]=extra
  [lock]=core
  [unlock]=core
  [locks]=core
  [quota]=core
  [open]=core
  [conflicts]=core
  [retry]=core
  [account]=core
  [logout]=core
  [config]=core
  [support]=core
  [nextcloudcmd]=core
  [watch]=core
  [limit]=core
  [unlimited]=core
  [network]=core
  [filters]=core
  [file]=extra
  [search]=extra
  [recent]=extra
  [comments]=extra
  [favorites]=extra
  [tags]=extra
  [server]=extra
  [hydrate]=core
  [provision]=core
  [logs]=core
  [edit]=extra
  [ignored]=core
  [announcements]=extra
  [preview]=extra
  [download]=core
  [update]=core
)

_SCIEBO_GLOBAL_SPECS=(
  '--profile|SCIEBO_PROFILE|value|0'
  '--trust|TLS_INSECURE|flag|0'
  '--non-interactive|SCIEBO_NON_INTERACTIVE|flag|0'
  '--debug|SCIEBO_DEBUG|flag|0'
  '--log-file|SCIEBO_LOG_FILE|value|0'
  '--confdir|SCIEBO_CONFDIR|value|1'
  '--log-dir|SCIEBO_LOG_DIR|value|1'
  '--log-expire|SCIEBO_LOG_EXPIRE_HOURS|value|1'
  '--version,-V|-|version|0'
)
