#!/usr/bin/env bash
# discover.sh - `sciebo discover`: scan roots.conf for git repositories,
# collapse nested repositories, and optionally write the generated manifest.
# Isolated: roots and the generated manifest live under the suite temp dir.
# shellcheck source-path=SCRIPTDIR
# shellcheck source=env.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/env.sh"

# Fixture: a workspace holding repos a and b, with a nested repo under a.
WS="${TMP}/disc-ws"
mkdir -p "${WS}/a/.git" "${WS}/a/nested/.git" "${WS}/b/.git"
printf 'ref: refs/heads/main\n' >"${WS}/a/.git/HEAD"
printf 'ref: refs/heads/main\n' >"${WS}/a/nested/.git/HEAD"
printf 'ref: refs/heads/main\n' >"${WS}/b/.git/HEAD"

# --- nested collapse, duplicate roots, and the generated header -----------
printf 'sync|%s|repos|4\nsync|%s|repos|4\n' "$WS" "$WS" >"$ROOTS_FILE"
expect_cli "discover: duplicate roots rc 0" 0 run_cli discover
expect_contains "discover: repo a emitted" "$CLI_OUT" "sync|${WS}/a|repos/a"
expect_contains "discover: repo b emitted" "$CLI_OUT" "sync|${WS}/b|repos/b"
expect_not_contains "discover: nested repo collapsed" "$CLI_OUT" "repos/a/nested"
expect_contains "discover: duplicate roots counted" "$CLI_OUT" "# 2 repositories from 2 root(s)."

# --- --write creates the manifest, mode 644, with the count header ---------
expect_cli "discover: --write rc 0" 0 run_cli discover --write
expect_contains "discover: --write reports the run" "$CLI_OUT" \
  "2 root(s) scanned, 2 repositories found"
expect_file "discover: --write creates the manifest" "$MANIFEST_GENERATED_FILE"
expect_eq "discover: manifest mode 644" "644" "$(file_mode "$MANIFEST_GENERATED_FILE")"
expect_contains "discover: manifest count header" \
  "$(cat "$MANIFEST_GENERATED_FILE")" "# 2 repositories from 2 root(s)."
expect_contains "discover: manifest generated header" \
  "$(cat "$MANIFEST_GENERATED_FILE")" "# Generated by 'sciebo discover --write' on"
expect_contains "discover: manifest holds repo a" \
  "$(cat "$MANIFEST_GENERATED_FILE")" "sync|${WS}/a|repos/a"

# --- a root that is itself a repository maps to remote_base ---------------
printf 'sync|%s|repos|4\n' "${WS}/b" >"$ROOTS_FILE"
expect_cli "discover: root-as-repo rc 0" 0 run_cli discover
expect_contains "discover: root-as-repo maps to remote_base" "$CLI_OUT" "sync|${WS}/b|repos"
expect_contains "discover: root-as-repo count header" "$CLI_OUT" "# 1 repositories from 1 root(s)."

# --- missing root fails with a warning, --write still writes the header ----
printf 'sync|%s|repos|2\n' "${TMP}/does-not-exist" >"$ROOTS_FILE"
expect_cli "discover: missing root rc 1" 1 run_cli discover
expect_contains "discover: missing root warning" "$CLI_OUT" "Root does not exist"
expect_cli "discover: --write with missing root rc 1" 1 run_cli discover --write
expect_file "discover: --write wrote the manifest despite the failure" "$MANIFEST_GENERATED_FILE"
expect_contains "discover: failed run writes the zero header" \
  "$(cat "$MANIFEST_GENERATED_FILE")" "# 0 repositories from 0 root(s)."

# --- a root without repositories warns but still succeeds -----------------
NOREPO="${TMP}/disc-norepo"
mkdir -p "$NOREPO"
printf 'sync|%s|repos|3\n' "$NOREPO" >"$ROOTS_FILE"
expect_cli "discover: repo-less root rc 0" 0 run_cli discover
expect_contains "discover: repo-less root warning" "$CLI_OUT" "No git repositories found"
expect_contains "discover: repo-less root count header" "$CLI_OUT" "# 0 repositories from 1 root(s)."

# --- an unrepresentable repository path is skipped and fails the run ------
# A tab cannot round-trip through the pipe/tab-separated record and manifest
# streams, so the repository is warned about and counted as a failure.
WS_TAB="${TMP}/disc-ws	tab"
mkdir -p "${WS_TAB}/.git"
printf 'sync|%s|repos|4\n' "$WS_TAB" >"$ROOTS_FILE"
expect_cli "discover: unrepresentable path rc 1" 1 run_cli discover
expect_contains "discover: unrepresentable path warned" "$CLI_OUT" "Unrepresentable repository path"
expect_not_contains "discover: unrepresentable path not emitted" "$CLI_OUT" "|${WS_TAB}|"

# --- invalid roots.conf entries are skipped, not fatal --------------------
printf 'bogus||repos|4\n' >"$ROOTS_FILE"
expect_cli "discover: invalid mode rc 1" 1 run_cli discover
expect_contains "discover: invalid mode warned" "$CLI_OUT" "invalid mode"

: >"$ROOTS_FILE"
expect_cli "discover: empty roots.conf rc 0" 0 run_cli discover
expect_contains "discover: empty roots.conf header" "$CLI_OUT" "# 0 repositories from 0 root(s)."

expect_cli "discover: --help rc 0" 0 run_cli discover --help
expect_contains "discover: usage documents --write" "$CLI_OUT" "--write"

finish
