#!/usr/bin/env bash
# gen-cli.sh - regenerate the CLI registry and the three shell completion
# scripts from the single declarative spec in lib/cli/sciebo.spec.
#
# Usage:
#   scripts/gen-cli.sh            write lib/cli/registry.sh and
#                                  completions/{sciebo.bash,_sciebo,
#                                  sciebo.fish} in place
#   scripts/gen-cli.sh --check    generate to a temp directory, validate the
#                                  spec (see below), and diff the four
#                                  generated files against the committed
#                                  ones; prints the diff and exits 1 on
#                                  drift, prints nothing and exits 0 when the
#                                  committed files match
#
# See lib/cli/sciebo.spec for the spec format. Output is deterministic: spec
# rows are emitted in file order, so a re-run with no spec change produces
# byte-identical files.
#
# Before generating anything (in both modes), the spec is validated against
# the rest of the tree, and a violation exits 1 with a message:
#   - every COMMAND row's <module> names a lib/commands/<module>.sh file
#     that exists (module "-", used only by the `help` row, is exempt),
#   - every lib/commands/*.sh file is named by at least one COMMAND row's
#     <module>,
#   - lib/cli/main.sh's usage_main lists exactly the spec's core-tier
#     commands under "Commands:" and extra-tier commands under "Extra
#     commands", in spec order (a grouped line like `lock SUB / unlock SUB`
#     or `limit / unlimited` counts as both of its names).

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="$ROOT/lib/cli/sciebo.spec"
HEADER="# Generated by scripts/gen-cli.sh from lib/cli/sciebo.spec; do not edit."

CHECK=0
case "${1:-}" in
  --check) CHECK=1 ;;
  '') ;;
  *)
    printf 'gen-cli: unknown argument: %s\n' "$1" >&2
    exit 2
    ;;
esac

[ -f "$SPEC" ] || {
  printf 'gen-cli: spec not found: %s\n' "$SPEC" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# Spec load: one flat array per row kind, each element the row's fields
# still joined by "|" (re-split with `IFS='|' read -r ... <<<"$row"` at the
# point of use). Preserves file order, which is what makes the emitters'
# output deterministic.

declare -a GLOBAL_ROWS=() COMMAND_ROWS=() SUB_ROWS=() OPT_ROWS=() POS_ROWS=()

while IFS= read -r _line || [ -n "$_line" ]; do
  case "$_line" in
    '' | '#'*) continue ;;
  esac
  case "$_line" in
    GLOBAL\|*) GLOBAL_ROWS+=("${_line#GLOBAL|}") ;;
    COMMAND\|*) COMMAND_ROWS+=("${_line#COMMAND|}") ;;
    SUB\|*) SUB_ROWS+=("${_line#SUB|}") ;;
    OPT\|*) OPT_ROWS+=("${_line#OPT|}") ;;
    POS\|*) POS_ROWS+=("${_line#POS|}") ;;
    *)
      printf 'gen-cli: bad spec line: %s\n' "$_line" >&2
      exit 1
      ;;
  esac
  # ENUM values are interpolated unescaped into the generated zsh/fish
  # completion code, which users' shells source, so they must stay plain
  # words: a quote or other shell syntax there would become code.
  case "$_line" in
    *'|ENUM:'*)
      _enum="${_line#*|ENUM:}"
      _enum="${_enum%%|*}"
      if [[ -z "$_enum" || "$_enum" == *[!A-Za-z0-9._,-]* || "$_enum" == *,, || "$_enum" == ,* || "$_enum" == *, ]]; then
        printf 'gen-cli: ENUM values must be comma-separated [A-Za-z0-9._-] words: %s\n' "$_line" >&2
        exit 1
      fi
      ;;
  esac
done <"$SPEC"
unset _line _enum

# is_dispatch_command CMD - true when CMD has at least one SUB row.
declare -A _IS_DISPATCH=()
for _row in "${SUB_ROWS[@]}"; do
  IFS='|' read -r _cmd _ <<<"$_row"
  _IS_DISPATCH["$_cmd"]=1
done
unset _row _cmd
is_dispatch_command() { [ -n "${_IS_DISPATCH[$1]:-}" ]; }

# zsh_escape TEXT - escape TEXT for a zsh _arguments spec string that the
# caller wraps in single quotes: backslash-escape the zsh-special ']', ':',
# and existing backslashes so a description carrying one of them (e.g.
# "0 or 1") stays literal, and close/reopen the quoting around an
# apostrophe ('\'') so "user's" cannot end the quoted word early.
zsh_escape() {
  local s="$1" q="'"
  s="${s//\\/\\\\}"
  s="${s//\]/\\]}"
  s="${s//:/\\:}"
  s="${s//"$q"/"'\\''"}"
  printf '%s' "$s"
}

# zsh_action ACTION LABEL - the zsh completion tail for a value/positional
# ACTION (":LABEL:<completer>").
zsh_action() {
  local action="$1" label="$2" completer=""
  case "$action" in
    NONE) completer="" ;;
    FILES) completer="_files" ;;
    DIRS) completer="_directories" ;;
    PROFILES) completer="_sciebo_profiles" ;;
    COMMANDS) completer="_sciebo_command_names" ;;
    ENUM:*)
      completer="${action#ENUM:}"
      completer="(${completer//,/ })"
      ;;
  esac
  printf ':%s:%s' "$(zsh_escape "$label")" "$completer"
}

# bash_action ACTION - the bash-side action keyword (none/files/dirs/
# profiles/commands/enum:a,b,c); bash's runtime helper does the dispatch.
bash_action() { printf '%s' "${1,,}"; }

# fish_action ACTION - "" for no fish completion, else a `-x -a 'a b c'`
# (enum) or `-r` (file/dir/profile/commands; fish has no directory-only
# completer, so DIRS gets the same plain `-r` as FILES/PROFILES/COMMANDS -
# matching the previous fish file's coverage) completion-argument suffix.
fish_action() {
  case "$1" in
    NONE) printf '' ;;
    ENUM:*) printf -- '-x -a %s' "'${1#ENUM:}'" | tr ',' ' ' ;;
    *) printf -- '-r' ;;
  esac
}

# ===========================================================================
# bash emitter
# ===========================================================================
emit_bash() {
  local row cmd sub names placeholder kind action desc
  local commands_list="" global_names="" dispatch_list=""

  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd _ _ _ <<<"$row"
    commands_list+="${commands_list:+ }${cmd}"
  done
  for row in "${GLOBAL_ROWS[@]}"; do
    IFS='|' read -r names _ _ _ _ <<<"$row"
    global_names+="${global_names:+ }${names//,/ }"
  done
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd _ _ _ <<<"$row"
    is_dispatch_command "$cmd" && dispatch_list+="${dispatch_list:+ }${cmd}"
  done

  cat <<BASH_HEADER
$HEADER
#
# bash completion for the 'sciebo' command (rclone-webdav-sync). Install: source this file from a
# bash-completion drop-in, or copy it into a completions directory (for
# example ~/.local/share/bash-completion/completions/sciebo).

_sciebo_commands='${commands_list}'
_sciebo_dispatch_commands='${dispatch_list}'
_sciebo_global_opts='${global_names}'

_sciebo_compgen() {
  local cur="\$1"
  shift
  # shellcheck disable=SC2207  # word-splitting the completion list is intended
  COMPREPLY=(\$(compgen -W "\$*" -- "\$cur"))
}

_sciebo_filedir() {
  local cur="\$1"
  if declare -F _filedir >/dev/null 2>&1; then
    _filedir
  else
    # shellcheck disable=SC2207  # word-splitting the file list is intended
    COMPREPLY=(\$(compgen -f -- "\$cur"))
  fi
}

_sciebo_dirs() {
  local cur="\$1"
  if declare -F _filedir >/dev/null 2>&1; then
    _filedir -d
  else
    # shellcheck disable=SC2207  # word-splitting the directory list is intended
    COMPREPLY=(\$(compgen -d -- "\$cur"))
  fi
}

_sciebo_project_root() {
  local src="\${BASH_SOURCE[0]}" dir
  case "\$src" in
    */*) ;;
    *) src="./\$src" ;;
  esac
  dir="\$(cd "\${src%/*}" 2>/dev/null && pwd)" || return 0
  dir="\${dir%/*}"
  [[ -n "\$dir" ]] || dir="/"
  [[ -d "\${dir}/config" ]] && printf '%s' "\$dir"
}

_sciebo_profile_names() {
  local root name base
  root="\$(_sciebo_project_root)"
  if [[ -n "\$root" && -d "\${root}/config/profiles" ]]; then
    for name in "\${root}/config/profiles"/*/; do
      [[ -d "\$name" ]] || continue
      base="\${name%/}"
      printf '%s\n' "\${base##*/}"
    done
  fi
  printf 'default\n'
}

_sciebo_profiles() {
  local cur="\$1" names
  names="\$(_sciebo_profile_names)"
  _sciebo_compgen "\$cur" "\$names"
}

_sciebo_is_dispatch() {
  case " \$_sciebo_dispatch_commands " in
    *" \$1 "*) return 0 ;;
  esac
  return 1
}

# _sciebo_complete_action ACTION CUR - dispatch a value/positional ACTION
# (none/files/dirs/profiles/commands/enum:a,b,c) against CUR.
_sciebo_complete_action() {
  local action="\$1" cur="\$2" list
  case "\$action" in
    files) _sciebo_filedir "\$cur" ;;
    dirs) _sciebo_dirs "\$cur" ;;
    profiles) _sciebo_profiles "\$cur" ;;
    commands) _sciebo_compgen "\$cur" "\$_sciebo_commands" ;;
    enum:*)
      list="\${action#enum:}"
      _sciebo_compgen "\$cur" "\${list//,/ }"
      ;;
    *) COMPREPLY=() ;;
  esac
}

BASH_HEADER

  # shellcheck disable=SC2016  # the printf argument is generated bash source, not this script's expansion
  printf '_sciebo_subs_for() {\n  case "$1" in\n'
  local last_cmd="" subs_line=""
  for row in "${SUB_ROWS[@]}"; do
    IFS='|' read -r cmd names _ <<<"$row"
    if [[ "$cmd" != "$last_cmd" ]]; then
      [[ -z "$last_cmd" ]] || printf "    '%s') printf '%%s\\\\n' '%s' ;;\n" "$last_cmd" "$subs_line"
      last_cmd="$cmd"
      subs_line="$names"
    else
      subs_line+=" $names"
    fi
  done
  [[ -z "$last_cmd" ]] || printf "    '%s') printf '%%s\\\\n' '%s' ;;\n" "$last_cmd" "$subs_line"
  printf "    *) printf '\\\\n' ;;\n  esac\n}\n\n"

  # _sciebo_options_for: grouped by "cmd:sub" key, in first-seen order.
  # shellcheck disable=SC2016  # the printf argument is generated bash source, not this script's expansion
  printf '_sciebo_options_for() {\n  local cmd="$1" sub="$2"\n  case "$cmd:$sub" in\n'
  declare -A opt_names_by_key=()
  local -a opt_key_order=()
  for row in "${OPT_ROWS[@]}"; do
    IFS='|' read -r cmd sub names placeholder kind action desc <<<"$row"
    local key="$cmd:$sub"
    if [[ -z "${opt_names_by_key[$key]+x}" ]]; then
      opt_key_order+=("$key")
      opt_names_by_key["$key"]="${names//,/ }"
    else
      opt_names_by_key["$key"]+=" ${names//,/ }"
    fi
  done
  local key
  for key in "${opt_key_order[@]}"; do
    printf "    '%s') printf '%%s\\\\n' '%s' ;;\n" "$key" "${opt_names_by_key[$key]}"
  done
  printf "    *) printf '\\\\n' ;;\n  esac\n}\n\n"

  # _sciebo_opt_lookup: one case arm per (cmd,sub,alias); falls back to the
  # global table (also one arm per alias) when nothing matched.
  # shellcheck disable=SC2016  # the printf argument is generated bash source, not this script's expansion
  printf '_sciebo_opt_lookup() {\n  local cmd="$1" sub="$2" flag="$3"\n  _SCIEBO_OPT_KIND=""\n  _SCIEBO_OPT_ACTION=""\n  case "$cmd:$sub:$flag" in\n'
  local alias
  for row in "${OPT_ROWS[@]}"; do
    IFS='|' read -r cmd sub names placeholder kind action desc <<<"$row"
    IFS=',' read -r -a aliases <<<"$names"
    for alias in "${aliases[@]}"; do
      printf "    '%s:%s:%s') _SCIEBO_OPT_KIND=%s; _SCIEBO_OPT_ACTION=%s ;;\n" \
        "$cmd" "$sub" "$alias" "$kind" "$(bash_action "$action")"
    done
  done
  # shellcheck disable=SC2016  # the printf argument is generated bash source, not this script's expansion
  printf '  esac\n  if [ -z "$_SCIEBO_OPT_KIND" ]; then\n    case "$flag" in\n'
  for row in "${GLOBAL_ROWS[@]}"; do
    IFS='|' read -r names _ kind action desc _ _ _ <<<"$row"
    IFS=',' read -r -a aliases <<<"$names"
    for alias in "${aliases[@]}"; do
      printf "      '%s') _SCIEBO_OPT_KIND=%s; _SCIEBO_OPT_ACTION=%s ;;\n" \
        "$alias" "$kind" "$(bash_action "$action")"
    done
  done
  printf '    esac\n  fi\n}\n\n'

  # _sciebo_pos_action: exact "cmd:sub:pos" matches first, then a "cmd:sub"
  # fallback table for the repeatable ("*") positions.
  # shellcheck disable=SC2016  # the printf argument is generated bash source, not this script's expansion
  printf '_sciebo_pos_action() {\n  local cmd="$1" sub="$2" pos="$3"\n  _SCIEBO_POS_ACTION=""\n  case "$cmd:$sub:$pos" in\n'
  local -a star_lines=()
  for row in "${POS_ROWS[@]}"; do
    IFS='|' read -r cmd sub idx label action <<<"$row"
    case "$idx" in
      '*') star_lines+=("$(printf "    '%s:%s') _SCIEBO_POS_ACTION=%s ;;\n" "$cmd" "$sub" "$(bash_action "$action")")") ;;
      \?*) printf "    '%s:%s:%s') _SCIEBO_POS_ACTION=%s ;;\n" "$cmd" "$sub" "$((${idx#?} - 1))" "$(bash_action "$action")" ;;
      *) printf "    '%s:%s:%s') _SCIEBO_POS_ACTION=%s ;;\n" "$cmd" "$sub" "$((idx - 1))" "$(bash_action "$action")" ;;
    esac
  done
  # shellcheck disable=SC2016  # the printf argument is generated bash source, not this script's expansion
  printf '  esac\n  if [ -z "$_SCIEBO_POS_ACTION" ]; then\n    case "$cmd:$sub" in\n'
  local line
  for line in "${star_lines[@]}"; do
    printf '%s' "$line"
  done
  printf '    esac\n  fi\n}\n\n'

  cat <<'BASH_MAIN'
_sciebo() {
  local cur cmd='' sub='-' w i pos=0 pending_flag='' is_dispatch=0 seen_sub=0
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"

  # --help/-h before the cursor ends completion.
  for ((i = 1; i < COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in
      -h | --help) return 0 ;;
    esac
  done

  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${COMP_WORDS[i]}"
    if [[ -n "$pending_flag" ]]; then
      pending_flag=''
      continue
    fi
    case "$w" in
      --*=*) continue ;;
      -*)
        _sciebo_opt_lookup "${cmd:--}" "$sub" "$w"
        case "$_SCIEBO_OPT_KIND" in
          value | optional-value | repeatable | two-arg) pending_flag="$w" ;;
        esac
        continue
        ;;
    esac
    if [[ -z "$cmd" ]]; then
      cmd="$w"
      if _sciebo_is_dispatch "$cmd"; then is_dispatch=1; else is_dispatch=0; fi
    elif [[ "$is_dispatch" -eq 1 && "$seen_sub" -eq 0 ]]; then
      sub="$w"
      seen_sub=1
    else
      pos=$((pos + 1))
    fi
  done

  # A "--flag=partial" at the cursor completes that flag's value inline,
  # for every valued option (not just a hardcoded pair).
  case "$cur" in
    --*=*)
      local flagname="${cur%%=*}" partial="${cur#*=}"
      _sciebo_opt_lookup "${cmd:--}" "$sub" "$flagname"
      case "$_SCIEBO_OPT_KIND" in
        value | optional-value | repeatable | two-arg)
          _sciebo_complete_action "$_SCIEBO_OPT_ACTION" "$partial"
          local j
          for j in "${!COMPREPLY[@]}"; do
            COMPREPLY[j]="${flagname}=${COMPREPLY[j]}"
          done
          ;;
      esac
      return 0
      ;;
  esac

  if [[ -n "$pending_flag" ]]; then
    _sciebo_opt_lookup "${cmd:--}" "$sub" "$pending_flag"
    # An optional-value option whose next word looks like a flag is not
    # given a value by the real parser (it falls back to its default and
    # the word is a fresh option instead); every other kind always
    # consumes the next word, matching opt_parse.
    if [[ "$_SCIEBO_OPT_KIND" != optional-value || "$cur" != -* ]]; then
      _sciebo_complete_action "$_SCIEBO_OPT_ACTION" "$cur"
      return 0
    fi
  fi

  if [[ -z "$cmd" ]]; then
    _sciebo_compgen "$cur" "$_sciebo_commands $_sciebo_global_opts"
    return 0
  fi

  if [[ "$cur" == -* ]]; then
    _sciebo_compgen "$cur" "$(_sciebo_options_for "$cmd" "$sub") $_sciebo_global_opts"
    return 0
  fi

  if [[ "$is_dispatch" -eq 1 && "$seen_sub" -eq 0 ]]; then
    _sciebo_compgen "$cur" "$(_sciebo_subs_for "$cmd")"
    return 0
  fi

  _sciebo_pos_action "$cmd" "$sub" "$pos"
  _sciebo_complete_action "$_SCIEBO_POS_ACTION" "$cur"
}

complete -F _sciebo sciebo
BASH_MAIN
}
# zsh_spec_lines NAMES PLACEHOLDER KIND ACTION DESC - print one zsh
# _arguments spec string per line (already single-quoted); more than one
# line when NAMES has more than one alias spelling (a plain multi-alias
# flag uses the brace form, e.g. '(-h --help)'{-h,--help}'[...]'; a
# multi-alias value option - long/short suffix forms differ - repeats the
# spec once per alias, each carrying a mutual-exclusion group instead).
zsh_spec_lines() {
  local names="$1" placeholder="$2" kind="$3" action="$4" desc="$5"
  local -a aliases
  IFS=',' read -r -a aliases <<<"$names"
  local edesc
  edesc="$(zsh_escape "$desc")"
  if [ "$kind" = flag ] && [ "${#aliases[@]}" -gt 1 ]; then
    printf "'(%s)'{%s}'[%s]'\n" "${names//,/ }" "$names" "$edesc"
    return
  fi
  local group=""
  [ "${#aliases[@]}" -gt 1 ] && group="(${names//,/ })"
  local alias star suffix tail body
  for alias in "${aliases[@]}"; do
    star=""
    suffix=""
    tail=""
    case "$kind" in
      flag) ;;
      repeatable)
        star="*"
        case "$alias" in --*) suffix="=" ;; esac
        tail="$(zsh_action "$action" "$placeholder")"
        ;;
      two-arg)
        case "$alias" in --*) suffix="=" ;; esac
        tail="$(zsh_action NONE "$placeholder")"
        ;;
      *)
        case "$alias" in --*) suffix="=" ;; esac
        tail="$(zsh_action "$action" "$placeholder")"
        ;;
    esac
    body="${group}${star}${alias}${suffix}[${edesc}]${tail}"
    printf "'%s'\n" "$body"
  done
}

# zsh_pos_spec IDX LABEL ACTION - one zsh positional spec string, already
# single-quoted (IDX is "N", "?N", or "*"; see lib/cli/sciebo.spec).
zsh_pos_spec() {
  local idx="$1" label="$2" action="$3" tail
  tail="$(zsh_action "$action" "$label")"
  case "$idx" in
    '*') printf "'*%s'" "$tail" ;;
    \?*) printf "':%s'" "$tail" ;;
    *) printf "'%s%s'" "$idx" "$tail" ;;
  esac
}

# zsh_emit_arguments_body CMD SUB INDENT - print one `_arguments
# ${_sciebo_global_specs[@]} ...` call (positionals first, then options,
# spec file order) for (CMD, SUB), indented by INDENT; a plain call with
# no trailing specs when neither has any rows.
zsh_emit_arguments_body() {
  local cmd="$1" sub="$2" indent="$3" row rcmd rsub
  local -a lines=()
  for row in "${POS_ROWS[@]}"; do
    IFS='|' read -r rcmd rsub idx label action <<<"$row"
    [ "$rcmd" = "$cmd" ] && [ "$rsub" = "$sub" ] || continue
    lines+=("$(zsh_pos_spec "$idx" "$label" "$action")")
  done
  for row in "${OPT_ROWS[@]}"; do
    IFS='|' read -r rcmd rsub names placeholder kind action desc <<<"$row"
    [ "$rcmd" = "$cmd" ] && [ "$rsub" = "$sub" ] || continue
    while IFS= read -r line; do
      lines+=("$line")
    done < <(zsh_spec_lines "$names" "$placeholder" "$kind" "$action" "$desc")
  done
  if [ "${#lines[@]}" -eq 0 ]; then
    # shellcheck disable=SC2016  # the printf argument is generated zsh source, not this script's expansion
    printf '%s_arguments ${_sciebo_global_specs[@]}\n' "$indent"
    return
  fi
  # shellcheck disable=SC2016  # the printf argument is generated zsh source, not this script's expansion
  printf '%s_arguments ${_sciebo_global_specs[@]} \\\n' "$indent"
  local i last=$((${#lines[@]} - 1))
  for i in "${!lines[@]}"; do
    if [ "$i" -eq "$last" ]; then
      printf '%s  %s\n' "$indent" "${lines[$i]}"
    else
      printf '%s  %s \\\n' "$indent" "${lines[$i]}"
    fi
  done
}

# zsh_emit_dispatch_function CMD - print the _sciebo_<cmd>() function that
# dispatches CMD's subcommands (the same shape as the previous hand-written
# file: a ->sub/->args _arguments split, a subs=() _describe list, and one
# `_arguments` call per subcommand).
zsh_emit_dispatch_function() {
  local cmd="$1" row rcmd rsub names placeholder kind action desc
  printf '_sciebo_%s() {\n' "$cmd"
  # shellcheck disable=SC2016  # the printf argument is generated zsh source, not this script's expansion
  printf '  local state\n  typeset -A opt_args\n  _arguments -C ${_sciebo_global_specs[@]} \\\n'
  for row in "${OPT_ROWS[@]}"; do
    IFS='|' read -r rcmd rsub names placeholder kind action desc <<<"$row"
    [ "$rcmd" = "$cmd" ] && [ "$rsub" = "-" ] || continue
    while IFS= read -r line; do
      printf '    %s \\\n' "$line"
    done < <(zsh_spec_lines "$names" "$placeholder" "$kind" "$action" "$desc")
  done
  printf "    '1:subcommand:->sub' \\\\\n"
  printf "    '*::argument:->args' && return 0\n"
  # shellcheck disable=SC2016  # the printf argument is generated zsh source, not this script's expansion
  printf '  case $state in\n    sub)\n      local -a subs\n      subs=(\n'
  for row in "${SUB_ROWS[@]}"; do
    IFS='|' read -r rcmd names desc <<<"$row"
    [ "$rcmd" = "$cmd" ] || continue
    printf "        '%s:%s'\n" "$names" "$(zsh_escape "$desc")"
  done
  printf "      )\n      _describe -t commands '%s subcommand' subs\n      ;;\n" "$cmd"
  # shellcheck disable=SC2016  # the printf argument is generated zsh source, not this script's expansion
  printf '    args)\n      case $words[1] in\n'
  for row in "${SUB_ROWS[@]}"; do
    IFS='|' read -r rcmd names desc <<<"$row"
    [ "$rcmd" = "$cmd" ] || continue
    printf '        %s)\n' "$names"
    zsh_emit_arguments_body "$cmd" "$names" "          "
    printf '          ;;\n'
  done
  printf '      esac\n      ;;\n  esac\n}\n\n'
}

# ===========================================================================
# zsh emitter
# ===========================================================================
emit_zsh() {
  local row cmd tier desc names placeholder kind action

  cat <<ZSH_HEADER
#compdef sciebo
$HEADER
#
# zsh completion for the 'sciebo' command (rclone-webdav-sync). Put this file on \$fpath as \`_sciebo\`;
# compinit then picks it up automatically.

typeset -ga _sciebo_global_specs
_sciebo_global_specs=(
ZSH_HEADER
  for row in "${GLOBAL_ROWS[@]}"; do
    IFS='|' read -r names placeholder kind action desc _ _ _ <<<"$row"
    while IFS= read -r line; do
      printf '  %s\n' "$line"
    done < <(zsh_spec_lines "$names" "$placeholder" "$kind" "$action" "$desc")
  done
  printf ')\n\ntypeset -ga _sciebo_commands\n_sciebo_commands=(\n'
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier _ desc <<<"$row"
    printf "  '%s:%s'\n" "$cmd" "$(zsh_escape "$desc")"
  done
  printf ')\n\n'

  cat <<'ZSH_STATIC'
_sciebo_project_root() {
  local dir=${${(%):-%x}:A:h:h}
  [[ -d $dir/config ]] && print -r -- $dir
}

_sciebo_profiles() {
  local root
  local -a profiles names
  profiles=(default)
  root=$(_sciebo_project_root)
  if [[ -n $root && -d $root/config/profiles ]]; then
    names=(${(f)"$(command ls -1 $root/config/profiles 2>/dev/null)"})
    profiles+=(${names:#})
  fi
  _describe -t profiles 'profile' profiles
}

_sciebo_command_names() {
  _describe -t commands 'sciebo command' _sciebo_commands
}

ZSH_STATIC

  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier _ desc <<<"$row"
    is_dispatch_command "$cmd" || continue
    zsh_emit_dispatch_function "$cmd"
  done

  cat <<'ZSH_MAIN_TOP'
_sciebo() {
  local state line context
  typeset -A opt_args
  local ret=1

  _arguments -C ${_sciebo_global_specs[@]} \
    '1:command:->command' \
    '*::argument:->args' && ret=0

  case $state in
    command)
      _describe -t commands 'sciebo command' _sciebo_commands
      ;;
    args)
      case $words[1] in
ZSH_MAIN_TOP

  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier _ desc <<<"$row"
    printf '        %s)\n' "$cmd"
    if is_dispatch_command "$cmd"; then
      printf '          _sciebo_%s\n' "$cmd"
    else
      zsh_emit_arguments_body "$cmd" "-" "          "
    fi
    printf '          ;;\n'
  done

  cat <<'ZSH_MAIN_BOTTOM'
      esac
      ;;
  esac

  return ret
}

ZSH_MAIN_BOTTOM

  printf '_sciebo "$@"\n'
}
# fish_escape TEXT - backslash-escape a single quote / backslash for a
# fish single-quoted string.
fish_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\'/\\\'}"
  printf '%s' "$s"
}

# fish_action_suffix ACTION REQUIRE - the trailing `complete` flags for a
# value/positional ACTION; REQUIRE=1 adds "-r" (an option that needs a
# value), REQUIRE=0 is for a bare positional.
fish_action_suffix() {
  local action="$1" require="$2" req=""
  [ "$require" = 1 ] && req=" -r"
  case "$action" in
    NONE | FILES) printf '%s' "$req" ;;
    DIRS) printf "%s -f -a '(__fish_complete_directories)'" "$req" ;;
    PROFILES) printf "%s -f -a '(__fish_sciebo_profiles)'" "$req" ;;
    COMMANDS) printf "%s -f -a '(__fish_sciebo_commands)'" "$req" ;;
    ENUM:*) printf "%s -f -a '%s'" "$req" "${action#ENUM:}" | tr ',' ' ' ;;
  esac
}

# fish_complete_lines CONDITION NAMES REQUIRE ACTION DESC - print one or
# more `complete -c sciebo ...` lines for an option (REQUIRE=1) or a
# global option; CONDITION is "" (always-on) or "-n '...'". A short+long
# alias pair collapses onto one line (`-s x -l name`); extra long aliases
# with no short (e.g. --resume,--continue) each get their own line.
fish_complete_lines() {
  local condition="$1" names="$2" require="$3" action="$4" desc="$5"
  local -a aliases
  IFS=',' read -r -a aliases <<<"$names"
  local short=""
  local -a longs=()
  local a
  for a in "${aliases[@]}"; do
    case "$a" in
      --*) longs+=("$a") ;;
      -*) [ -n "$short" ] || short="$a" ;;
    esac
  done
  local edesc dsuffix asuffix
  edesc="$(fish_escape "$desc")"
  dsuffix=""
  [ -n "$edesc" ] && dsuffix=" -d '${edesc}'"
  asuffix="$(fish_action_suffix "$action" "$require")"
  if [ "${#longs[@]}" -eq 0 ]; then
    printf 'complete -c sciebo%s -s %s%s%s\n' "${condition:+ $condition}" "${short#-}" "$dsuffix" "$asuffix"
    return
  fi
  local first=1 lf
  for lf in "${longs[@]}"; do
    if [ "$first" -eq 1 ] && [ -n "$short" ]; then
      printf 'complete -c sciebo%s -s %s -l %s%s%s\n' "${condition:+ $condition}" "${short#-}" "${lf#--}" "$dsuffix" "$asuffix"
    else
      printf 'complete -c sciebo%s -l %s%s%s\n' "${condition:+ $condition}" "${lf#--}" "$dsuffix" "$asuffix"
    fi
    first=0
  done
}

# ===========================================================================
# fish emitter
# ===========================================================================
emit_fish() {
  local row cmd tier desc names placeholder kind action rcmd rsub

  cat <<FISH_HEADER
$HEADER
#
# fish completion for the 'sciebo' command (rclone-webdav-sync). Install by copying this file to
# ~/.config/fish/completions/sciebo.fish, or add completions/ to
# \$fish_complete_path.

function __fish_sciebo_commands
    printf '%s\\n' \\
FISH_HEADER
  local n=0 total=${#COMMAND_ROWS[@]}
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier _ desc <<<"$row"
    n=$((n + 1))
    if [ "$n" -eq "$total" ]; then
      printf '        %s\n' "$cmd"
    else
      printf '        %s \\\n' "$cmd"
    fi
  done
  printf 'end\n\n'

  # shellcheck disable=SC2016  # the printf argument is generated fish source, not this script's expansion
  printf 'function __fish_sciebo_is_dispatch\n    switch $argv[1]\n        case'
  local dispatch_list=""
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier _ desc <<<"$row"
    is_dispatch_command "$cmd" && dispatch_list+=" $cmd"
  done
  printf '%s\n            return 0\n    end\n    return 1\nend\n\n' "$dispatch_list"

  # shellcheck disable=SC2016  # the printf argument is generated fish source, not this script's expansion
  printf 'function __fish_sciebo_opt_takes_value\n    switch "$argv[1]:$argv[2]:$argv[3]"\n'
  for row in "${OPT_ROWS[@]}"; do
    IFS='|' read -r rcmd rsub names placeholder kind action desc <<<"$row"
    [ "$kind" = flag ] && continue
    local alias
    IFS=',' read -r -a _aliases <<<"$names"
    for alias in "${_aliases[@]}"; do
      printf "        case '%s:%s:%s'\n            return 0\n" "$rcmd" "$rsub" "$alias"
    done
  done
  # shellcheck disable=SC2016  # the printf argument is generated fish source, not this script's expansion
  printf '    end\n    switch $argv[3]\n        case'
  local global_value_list=""
  for row in "${GLOBAL_ROWS[@]}"; do
    IFS='|' read -r names placeholder kind action desc _ _ _ <<<"$row"
    [ "$kind" = flag ] && continue
    global_value_list+=" ${names//,/ }"
  done
  printf '%s\n            return 0\n    end\n    return 1\nend\n\n' "$global_value_list"

  cat <<'FISH_STATIC'
function __fish_sciebo_profiles
    set -l self (status --current-filename)
    set -l dir (dirname $self)
    set -l root (dirname $dir)
    if test -d $root/config/profiles
        for p in $root/config/profiles/*/
            basename $p
        end
    end
    echo default
end

# __fish_sciebo_context - echoes three lines (cmd, sub, pos): the command,
# its subcommand ("-" when CMD has none, or none was typed yet), and the
# count of bare positional words consumed so far at that (cmd, sub) level.
# Skips option tokens, and the word right after one that
# __fish_sciebo_opt_takes_value says consumes a value - so a value that
# happens to spell a command/subcommand name is never mistaken for one
# (the bug the previous __fish_seen_subcommand_from-based file had).
function __fish_sciebo_context
    set -l tokens (commandline -opc)
    set -e tokens[1]
    set -l cmd ''
    set -l sub '-'
    set -l is_dispatch 0
    set -l seen_sub 0
    set -l pos 0
    set -l skip 0
    for t in $tokens
        if test $skip -eq 1
            set skip 0
            continue
        end
        switch $t
            case '-*'
                if __fish_sciebo_opt_takes_value $cmd $sub $t
                    set skip 1
                end
                continue
        end
        if test -z "$cmd"
            set cmd $t
            if __fish_sciebo_is_dispatch $cmd
                set is_dispatch 1
            end
        else if test $is_dispatch -eq 1 -a $seen_sub -eq 0
            set sub $t
            set seen_sub 1
        else
            set pos (math $pos + 1)
        end
    end
    echo $cmd
    echo $sub
    echo $pos
end

function __fish_sciebo_at
    set -l ctx (__fish_sciebo_context)
    test "$ctx[1]" = "$argv[1]" -a "$ctx[2]" = "$argv[2]"
end

function __fish_sciebo_cmd_is
    set -l ctx (__fish_sciebo_context)
    test "$ctx[1]" = "$argv[1]"
end

function __fish_sciebo_needs_command
    set -l ctx (__fish_sciebo_context)
    test -z "$ctx[1]"
end

function __fish_sciebo_needs_sub
    set -l ctx (__fish_sciebo_context)
    test -n "$ctx[1]" -a "$ctx[2]" = '-'
    and __fish_sciebo_is_dispatch $ctx[1]
end

FISH_STATIC

  printf "complete -c sciebo -f -n __fish_sciebo_needs_command -a '(__fish_sciebo_commands)'\n\n"

  for row in "${GLOBAL_ROWS[@]}"; do
    IFS='|' read -r names placeholder kind action desc _ _ _ <<<"$row"
    local require=0
    [ "$kind" = flag ] || require=1
    fish_complete_lines "" "$names" "$require" "$action" "$desc"
  done
  printf '\n'

  for row in "${COMMAND_ROWS[@]}"; do
    # shellcheck disable=SC2034  # tier is read for field alignment; validate_spec checks it against usage_main
    IFS='|' read -r cmd tier _ desc <<<"$row"
    if is_dispatch_command "$cmd"; then
      local subs_list=""
      local srow
      for srow in "${SUB_ROWS[@]}"; do
        # shellcheck disable=SC2034  # sdesc is read for field alignment; the fish subcommand list has no descriptions
        IFS='|' read -r rcmd names sdesc <<<"$srow"
        [ "$rcmd" = "$cmd" ] || continue
        subs_list+="${subs_list:+ }${names}"
      done
      printf "complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is %s' -a '%s'\n" "$cmd" "$subs_list"
      for srow in "${SUB_ROWS[@]}"; do
        # shellcheck disable=SC2034  # sdesc is read for field alignment; the fish subcommand list has no descriptions
        IFS='|' read -r rcmd names sdesc <<<"$srow"
        [ "$rcmd" = "$cmd" ] || continue
        fish_emit_opts_and_pos "$cmd" "$names"
      done
    else
      fish_emit_opts_and_pos "$cmd" "-"
    fi
  done

  printf '\n'
}

# fish_emit_opts_and_pos CMD SUB - print the option and positional
# `complete` lines for (CMD, SUB), each gated by `__fish_sciebo_at CMD SUB`.
fish_emit_opts_and_pos() {
  local cmd="$1" sub="$2" row rcmd rsub names placeholder kind action desc idx label
  local cond="-n '__fish_sciebo_at $cmd $sub'"
  for row in "${OPT_ROWS[@]}"; do
    IFS='|' read -r rcmd rsub names placeholder kind action desc <<<"$row"
    [ "$rcmd" = "$cmd" ] && [ "$rsub" = "$sub" ] || continue
    local require=0
    [ "$kind" = flag ] || require=1
    fish_complete_lines "$cond" "$names" "$require" "$action" "$desc"
  done
  for row in "${POS_ROWS[@]}"; do
    IFS='|' read -r rcmd rsub idx label action <<<"$row"
    [ "$rcmd" = "$cmd" ] && [ "$rsub" = "$sub" ] || continue
    [ "$action" = NONE ] && continue
    local suffix
    suffix="$(fish_action_suffix "$action" 0)"
    [ -n "$suffix" ] && printf 'complete -c sciebo %s%s\n' "$cond" "$suffix"
  done
}

# ===========================================================================
# registry emitter - lib/cli/registry.sh: data only (SCIEBO_COMMANDS, the
# command-to-module and tier maps, and the runtime _SCIEBO_GLOBAL_SPECS
# table), no functions. The `help` row (COMMAND module "-") is excluded from
# all three command tables, matching the previous hand-written COMMANDS
# string; a GLOBAL row with an empty <env-var> (only -h/--help) is excluded
# from _SCIEBO_GLOBAL_SPECS, matching the previous hand-written array.
# ===========================================================================
emit_registry() {
  local row cmd tier module desc names env rkind early
  local commands_list=""

  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier module desc <<<"$row"
    [ "$module" = "-" ] && continue
    commands_list+="${commands_list:+ }${cmd}"
  done

  cat <<REGISTRY_HEADER
#!/bin/bash
$HEADER
#
# The runtime CLI registry: the command list, the command-to-module map, the
# tier map, and the global-option table - lib/sciebo.sh and lib/cli/main.sh
# source this file (the cli layer, before lib/cli/main.sh itself). Data
# only, no functions: see lib/cli/sciebo.spec for what each table means and
# lib/cli/main.sh/lib/sciebo.sh for how they are consumed.

# shellcheck disable=SC2034  # read by lib/cli/main.sh's is_command
SCIEBO_COMMANDS="${commands_list}"

REGISTRY_HEADER

  printf '# shellcheck disable=SC2034  # read by lib/sciebo.sh'"'"'s sciebo_command_module\n'
  printf 'declare -gA SCIEBO_COMMAND_MODULE=(\n'
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier module desc <<<"$row"
    [ "$module" = "-" ] && continue
    printf '  [%s]=%s\n' "$cmd" "$module"
  done
  printf ')\n\n'

  printf '# shellcheck disable=SC2034  # part of the generated registry; not read by the runtime dispatch today, kept for tooling that needs the core/extra split without re-deriving it from the spec\n'
  printf 'declare -gA SCIEBO_COMMAND_TIER=(\n'
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier module desc <<<"$row"
    [ "$module" = "-" ] && continue
    printf '  [%s]=%s\n' "$cmd" "$tier"
  done
  printf ')\n\n'

  printf '_SCIEBO_GLOBAL_SPECS=(\n'
  for row in "${GLOBAL_ROWS[@]}"; do
    IFS='|' read -r names _ _ _ _ env rkind early <<<"$row"
    [ -n "$env" ] || continue
    printf "  '%s|%s|%s|%s'\n" "$names" "$env" "$rkind" "$early"
  done
  printf ')\n'
}

# ===========================================================================
# spec validation - run before every generation (plain or --check): a
# violation exits the whole script with a message, so a bad spec is caught
# even by a plain `scripts/gen-cli.sh` run, not only `--check`.
# ===========================================================================

# validate_spec - checks described in this script's own header comment.
# Prints one "gen-cli:"-prefixed message per violation to stderr and returns
# non-zero when any is found.
validate_spec() {
  local errors=0 row cmd tier module desc

  # --- every COMMAND module file exists; every lib/commands/*.sh is used --
  declare -A _used_modules=()
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier module desc <<<"$row"
    [ "$module" = "-" ] && continue
    if [ ! -f "$ROOT/lib/commands/${module}.sh" ]; then
      printf 'gen-cli: COMMAND %s names module "%s", but lib/commands/%s.sh does not exist\n' \
        "$cmd" "$module" "$module" >&2
      errors=$((errors + 1))
    fi
    _used_modules["$module"]=1
  done
  local modfile modbase
  for modfile in "$ROOT"/lib/commands/*.sh; do
    [ -f "$modfile" ] || continue
    modbase="$(basename "$modfile" .sh)"
    if [ -z "${_used_modules[$modbase]:-}" ]; then
      printf 'gen-cli: lib/commands/%s.sh is not named as the module of any COMMAND row\n' "$modbase" >&2
      errors=$((errors + 1))
    fi
  done

  # --- usage_main's Commands:/Extra commands sections vs the spec, in order
  local -a expected_core=() expected_extra=()
  for row in "${COMMAND_ROWS[@]}"; do
    IFS='|' read -r cmd tier module desc <<<"$row"
    [ "$module" = "-" ] && continue
    case "$tier" in
      core) expected_core+=("$cmd") ;;
      extra) expected_extra+=("$cmd") ;;
    esac
  done

  local -a actual_core=() actual_extra=()
  local section name
  while IFS=$'\t' read -r section name; do
    [ -n "$section" ] || continue
    if [ "$section" = core ]; then
      actual_core+=("$name")
    else
      actual_extra+=("$name")
    fi
  done < <(awk '
    /^usage_main\(\)/ { active = 1 }
    active && /^}/ { exit }
    active && /^Commands:/ { section = "core"; next }
    active && /^Extra commands/ { section = "extra"; next }
    active && /^[[:space:]]*$/ { section = ""; next }
    active && section != "" && /^  [^ ]/ {
      line = $0
      sub(/^  /, "", line)
      sub(/[ \t][ \t]+.*$/, "", line)
      n = split(line, parts, " / ")
      for (i = 1; i <= n; i++) {
        name = parts[i]
        sub(/[ \t].*$/, "", name)
        print section "\t" name
      }
    }
  ' "$ROOT/lib/cli/main.sh")

  # _validate_seq LABEL EXPECTED_ARR ACTUAL_ARR - compare two name sequences
  # in order; a length or element mismatch is one error with both sequences
  # printed for a human to diff by eye.
  _validate_seq() {
    local label="$1" expname="$2" actname="$3"
    local -n _exp="$expname" _act="$actname"
    if [ "${#_exp[@]}" -ne "${#_act[@]}" ] || [ "${_exp[*]}" != "${_act[*]}" ]; then
      printf 'gen-cli: usage_main'"'"'s "%s" section does not list the spec'"'"'s commands in order\n  spec:  %s\n  usage: %s\n' \
        "$label" "${_exp[*]}" "${_act[*]}" >&2
      errors=$((errors + 1))
    fi
  }
  _validate_seq "Commands:" expected_core actual_core
  _validate_seq "Extra commands" expected_extra actual_extra

  [ "$errors" -eq 0 ]
}

# ---------------------------------------------------------------------------
# Driver: validate the spec, then write in place or diff against the
# committed files with --check. Validation runs in both modes, so a bad
# spec is caught even by a plain `scripts/gen-cli.sh` run.

validate_spec || exit 1

TMPDIR_GEN="$(mktemp -d "${TMPDIR:-/tmp}/sciebo-gen-cli.XXXXXX")"
trap 'rm -rf "$TMPDIR_GEN"' EXIT

emit_registry >"$TMPDIR_GEN/registry.sh"
emit_bash >"$TMPDIR_GEN/sciebo.bash"
emit_zsh >"$TMPDIR_GEN/_sciebo"
emit_fish >"$TMPDIR_GEN/sciebo.fish"

if [ "$CHECK" -eq 1 ]; then
  status=0
  if ! diff -u "$ROOT/lib/cli/registry.sh" "$TMPDIR_GEN/registry.sh"; then
    status=1
  fi
  for name in sciebo.bash _sciebo sciebo.fish; do
    if ! diff -u "$ROOT/completions/$name" "$TMPDIR_GEN/$name"; then
      status=1
    fi
  done
  if [ "$status" -eq 0 ]; then
    exit 0
  fi
  printf 'gen-cli --check: lib/cli/registry.sh and/or completions/{sciebo.bash,_sciebo,sciebo.fish} are out of date; run scripts/gen-cli.sh\n' >&2
  exit 1
fi

cp "$TMPDIR_GEN/registry.sh" "$ROOT/lib/cli/registry.sh"
cp "$TMPDIR_GEN/sciebo.bash" "$ROOT/completions/sciebo.bash"
cp "$TMPDIR_GEN/_sciebo" "$ROOT/completions/_sciebo"
cp "$TMPDIR_GEN/sciebo.fish" "$ROOT/completions/sciebo.fish"
printf 'wrote lib/cli/registry.sh, completions/sciebo.bash, completions/_sciebo, completions/sciebo.fish\n'
