# Generated by scripts/gen-completions.sh from completions/sciebo.spec; do not edit.
#
# fish completion for the sciebo CLI. Install by copying this file to
# ~/.config/fish/completions/sciebo.fish, or add completions/ to
# $fish_complete_path.

function __fish_sciebo_commands
    printf '%s\n' \
        setup \
        doctor \
        discover \
        list \
        check \
        sync \
        verify \
        status \
        pause \
        resume \
        folders \
        mount \
        umount \
        mounts \
        cleanup \
        schedule \
        trash \
        versions \
        share \
        notifications \
        activity \
        presence \
        lock \
        unlock \
        locks \
        quota \
        open \
        conflicts \
        retry \
        account \
        logout \
        config \
        support \
        nextcloudcmd \
        watch \
        limit \
        unlimited \
        network \
        filters \
        file \
        search \
        recent \
        comments \
        favorites \
        tags \
        server \
        hydrate \
        provision \
        logs \
        edit \
        ignored \
        announcements \
        preview \
        download \
        update \
        help
end

function __fish_sciebo_is_dispatch
    switch $argv[1]
        case folders schedule trash share presence account config filters file tags server logs
            return 0
    end
    return 1
end

function __fish_sciebo_opt_takes_value
    switch "$argv[1]:$argv[2]:$argv[3]"
        case 'setup:-:--url'
            return 0
        case 'setup:-:--proxy'
            return 0
        case 'check:-:--only'
            return 0
        case 'sync:-:--only'
            return 0
        case 'verify:-:--only'
            return 0
        case 'status:-:--only'
            return 0
        case 'status:-:--history'
            return 0
        case 'status:-:--watch'
            return 0
        case 'pause:-:--for'
            return 0
        case 'folders:choose:--depth'
            return 0
        case 'folders:choose:--local-root'
            return 0
        case 'folders:choose:--mode'
            return 0
        case 'folders:add:--remote'
            return 0
        case 'folders:add:--local'
            return 0
        case 'folders:add:--mode'
            return 0
        case 'folders:add:--include'
            return 0
        case 'folders:add:--exclude'
            return 0
        case 'folders:add:--local-root'
            return 0
        case 'folders:import:--remote'
            return 0
        case 'folders:import:--local'
            return 0
        case 'folders:import:--mode'
            return 0
        case 'folders:import:--local-root'
            return 0
        case 'folders:edit:--local'
            return 0
        case 'folders:edit:--remote'
            return 0
        case 'folders:edit:--include'
            return 0
        case 'folders:edit:--exclude'
            return 0
        case 'folders:edit:--mode'
            return 0
        case 'mount:-:--folder'
            return 0
        case 'mount:-:--mountpoint'
            return 0
        case 'umount:-:--folder'
            return 0
        case 'umount:-:--mountpoint'
            return 0
        case 'mounts:-:--folder'
            return 0
        case 'cleanup:-:--keep'
            return 0
        case 'schedule:install:--profiles'
            return 0
        case 'versions:-:--download'
            return 0
        case 'versions:-:--output'
            return 0
        case 'versions:-:--restore'
            return 0
        case 'versions:-:--delete'
            return 0
        case 'share:link:--password'
            return 0
        case 'share:link:--expire'
            return 0
        case 'share:link:--note'
            return 0
        case 'share:link:--permissions'
            return 0
        case 'share:link:--label'
            return 0
        case 'share:link:--download'
            return 0
        case 'share:copy-link:--password'
            return 0
        case 'share:copy-link:--expire'
            return 0
        case 'share:copy-link:--note'
            return 0
        case 'share:copy-link:--permissions'
            return 0
        case 'share:copy-link:--label'
            return 0
        case 'share:copy-link:--download'
            return 0
        case 'share:user:--permissions'
            return 0
        case 'share:user:--note'
            return 0
        case 'share:group:--permissions'
            return 0
        case 'share:group:--note'
            return 0
        case 'share:guest:--permissions'
            return 0
        case 'share:guest:--note'
            return 0
        case 'share:circle:--permissions'
            return 0
        case 'share:circle:--note'
            return 0
        case 'share:talk:--permissions'
            return 0
        case 'share:talk:--note'
            return 0
        case 'share:deck:--permissions'
            return 0
        case 'share:deck:--note'
            return 0
        case 'share:remote:--permissions'
            return 0
        case 'share:remote:--note'
            return 0
        case 'share:email:--permissions'
            return 0
        case 'share:email:--note'
            return 0
        case 'share:email:--password'
            return 0
        case 'share:email:--expire'
            return 0
        case 'share:update:--password'
            return 0
        case 'share:update:--expire'
            return 0
        case 'share:update:--note'
            return 0
        case 'share:update:--permissions'
            return 0
        case 'share:update:--label'
            return 0
        case 'share:update:--download'
            return 0
        case 'notifications:-:--limit'
            return 0
        case 'notifications:-:--app'
            return 0
        case 'notifications:-:--type'
            return 0
        case 'notifications:-:--action'
            return 0
        case 'notifications:-:--delete'
            return 0
        case 'notifications:-:--watch'
            return 0
        case 'activity:-:--limit'
            return 0
        case 'activity:-:--since'
            return 0
        case 'presence:set:--message'
            return 0
        case 'presence:set:--emoji'
            return 0
        case 'presence:set:--clear-after'
            return 0
        case 'conflicts:-:--resolve'
            return 0
        case 'conflicts:-:--only'
            return 0
        case 'conflicts:-:--kind'
            return 0
        case 'account:add:--remote'
            return 0
        case 'account:add:--base'
            return 0
        case 'account:import:--nextcloud-cfg'
            return 0
        case 'account:import:--profile'
            return 0
        case 'account:avatar:--output'
            return 0
        case 'account:avatar:--size'
            return 0
        case 'support:-:--output'
            return 0
        case 'nextcloudcmd:-:--path'
            return 0
        case 'nextcloudcmd:-:--confdir'
            return 0
        case 'nextcloudcmd:-:--user'
            return 0
        case 'nextcloudcmd:-:-u'
            return 0
        case 'nextcloudcmd:-:--password'
            return 0
        case 'nextcloudcmd:-:-p'
            return 0
        case 'nextcloudcmd:-:--password-fd'
            return 0
        case 'nextcloudcmd:-:--httpproxy'
            return 0
        case 'nextcloudcmd:-:--exclude'
            return 0
        case 'nextcloudcmd:-:--exclude-anchored'
            return 0
        case 'nextcloudcmd:-:--unsyncedfolders'
            return 0
        case 'nextcloudcmd:-:--max-sync-retries'
            return 0
        case 'nextcloudcmd:-:--uplimit'
            return 0
        case 'nextcloudcmd:-:--downlimit'
            return 0
        case 'watch:-:--interval'
            return 0
        case 'watch:-:--debounce'
            return 0
        case 'watch:-:--only'
            return 0
        case 'watch:-:--remote-interval'
            return 0
        case 'watch:-:--backend'
            return 0
        case 'limit:-:--up'
            return 0
        case 'limit:-:--down'
            return 0
        case 'limit:-:--until'
            return 0
        case 'file:activity:--limit'
            return 0
        case 'search:-:--limit'
            return 0
        case 'recent:-:--since'
            return 0
        case 'recent:-:--limit'
            return 0
        case 'comments:-:--limit'
            return 0
        case 'hydrate:-:--dest'
            return 0
        case 'provision:-:--userid'
            return 0
        case 'provision:-:--apppassword'
            return 0
        case 'provision:-:--apppassword-fd'
            return 0
        case 'provision:-:--serverurl'
            return 0
        case 'provision:-:--localdirpath'
            return 0
        case 'provision:-:--remotedirpath'
            return 0
        case 'provision:-:--isvfsenabled'
            return 0
        case 'provision:-:--profile'
            return 0
        case 'logs:show:--lines'
            return 0
        case 'logs:tail:--lines'
            return 0
        case 'edit:-:--editor'
            return 0
        case 'ignored:-:--source'
            return 0
        case 'announcements:-:--limit'
            return 0
        case 'preview:-:--output'
            return 0
        case 'preview:-:--size'
            return 0
    end
    switch $argv[3]
        case --profile --log-file --confdir --log-dir --log-expire
            return 0
    end
    return 1
end

function __fish_sciebo_profiles
    set -l self (status --current-filename)
    set -l dir (dirname $self)
    set -l root (dirname $dir)
    if test -d $root/config/profiles
        for p in $root/config/profiles/*/
            basename $p
        end
    end
    echo default
end

# __fish_sciebo_context - echoes three lines (cmd, sub, pos): the command,
# its subcommand ("-" when CMD has none, or none was typed yet), and the
# count of bare positional words consumed so far at that (cmd, sub) level.
# Skips option tokens, and the word right after one that
# __fish_sciebo_opt_takes_value says consumes a value - so a value that
# happens to spell a command/subcommand name is never mistaken for one
# (the bug the previous __fish_seen_subcommand_from-based file had).
function __fish_sciebo_context
    set -l tokens (commandline -opc)
    set -e tokens[1]
    set -l cmd ''
    set -l sub '-'
    set -l is_dispatch 0
    set -l seen_sub 0
    set -l pos 0
    set -l skip 0
    for t in $tokens
        if test $skip -eq 1
            set skip 0
            continue
        end
        switch $t
            case '-*'
                if __fish_sciebo_opt_takes_value $cmd $sub $t
                    set skip 1
                end
                continue
        end
        if test -z "$cmd"
            set cmd $t
            if __fish_sciebo_is_dispatch $cmd
                set is_dispatch 1
            end
        else if test $is_dispatch -eq 1 -a $seen_sub -eq 0
            set sub $t
            set seen_sub 1
        else
            set pos (math $pos + 1)
        end
    end
    echo $cmd
    echo $sub
    echo $pos
end

function __fish_sciebo_at
    set -l ctx (__fish_sciebo_context)
    test "$ctx[1]" = "$argv[1]" -a "$ctx[2]" = "$argv[2]"
end

function __fish_sciebo_cmd_is
    set -l ctx (__fish_sciebo_context)
    test "$ctx[1]" = "$argv[1]"
end

function __fish_sciebo_needs_command
    set -l ctx (__fish_sciebo_context)
    test -z "$ctx[1]"
end

function __fish_sciebo_needs_sub
    set -l ctx (__fish_sciebo_context)
    test -n "$ctx[1]" -a "$ctx[2]" = '-'
    and __fish_sciebo_is_dispatch $ctx[1]
end

complete -c sciebo -f -n __fish_sciebo_needs_command -a '(__fish_sciebo_commands)'

complete -c sciebo -s h -l help -d 'show help'
complete -c sciebo -l profile -d 'select a profile' -r -f -a '(__fish_sciebo_profiles)'
complete -c sciebo -l trust -d 'accept invalid TLS certificates'
complete -c sciebo -l non-interactive -d 'never prompt; fail or skip instead'
complete -c sciebo -l debug -d 'verbose rclone/HTTP output'
complete -c sciebo -l log-file -d 'write the rclone log here' -r
complete -c sciebo -l confdir -d 'configuration and state directory' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -l log-dir -d 'write run logs here' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -l log-expire -d 'delete logs older than this many hours' -r
complete -c sciebo -s V -l version -d 'show the version'

complete -c sciebo -n '__fish_sciebo_at setup -' -l login -d 'authenticate with the Nextcloud Login Flow v2'
complete -c sciebo -n '__fish_sciebo_at setup -' -l url -d 'base URL for --login' -r
complete -c sciebo -n '__fish_sciebo_at setup -' -l rotate -d 'fetch a fresh app password for the configured remote'
complete -c sciebo -n '__fish_sciebo_at setup -' -l no-keychain -d 'store the obscured password in the rclone config'
complete -c sciebo -n '__fish_sciebo_at setup -' -l proxy -d 'proxy URL for this setup run' -r
complete -c sciebo -n '__fish_sciebo_at setup -' -l crypt -d 'create the crypt remote wrapping the WebDAV remote'
complete -c sciebo -n '__fish_sciebo_at doctor -' -l offline -d 'skip network checks'
complete -c sciebo -n '__fish_sciebo_at doctor -' -l json -d 'print a JSON document instead of the text report'
complete -c sciebo -n '__fish_sciebo_at discover -' -l write -d 'write config/sources.generated.conf'
complete -c sciebo -n '__fish_sciebo_at list -' -l json -d 'print the valid sources as JSON'
complete -c sciebo -n '__fish_sciebo_at check -' -l apply -d 'transfer data (default for sync; check stays a dry run)'
complete -c sciebo -n '__fish_sciebo_at check -' -l dry-run -d 'explicit dry run (default for check)'
complete -c sciebo -n '__fish_sciebo_at check -' -l only -d 'run only this source' -r
complete -c sciebo -n '__fish_sciebo_at check -' -l list -d 'print the parsed sources and exit (same as `sciebo list`)'
complete -c sciebo -n '__fish_sciebo_at check -' -l resync -d 'allow rclone bisync --resync'
complete -c sciebo -n '__fish_sciebo_at check -' -l yes -d 'ignore the MAX_DOWNLOAD_SIZE and delete guards'
complete -c sciebo -n '__fish_sciebo_at check -' -l metered-ok -d 'run even on a metered connection'
complete -c sciebo -n '__fish_sciebo_at check -' -l quiet -d 'only print failures, warnings, and the summary'
complete -c sciebo -n '__fish_sciebo_at check -' -l no-lock -d 'do not take the run lock'
complete -c sciebo -n '__fish_sciebo_at check -' -l force -d 'run even while paused'
complete -c sciebo -n '__fish_sciebo_at sync -' -l apply -d 'transfer data (default for sync; check stays a dry run)'
complete -c sciebo -n '__fish_sciebo_at sync -' -l dry-run -d 'explicit dry run (default for check)'
complete -c sciebo -n '__fish_sciebo_at sync -' -l only -d 'run only this source' -r
complete -c sciebo -n '__fish_sciebo_at sync -' -l list -d 'print the parsed sources and exit (same as `sciebo list`)'
complete -c sciebo -n '__fish_sciebo_at sync -' -l resync -d 'allow rclone bisync --resync'
complete -c sciebo -n '__fish_sciebo_at sync -' -l yes -d 'ignore the MAX_DOWNLOAD_SIZE and delete guards'
complete -c sciebo -n '__fish_sciebo_at sync -' -l metered-ok -d 'run even on a metered connection'
complete -c sciebo -n '__fish_sciebo_at sync -' -l quiet -d 'only print failures, warnings, and the summary'
complete -c sciebo -n '__fish_sciebo_at sync -' -l no-lock -d 'do not take the run lock'
complete -c sciebo -n '__fish_sciebo_at sync -' -l force -d 'run even while paused'
complete -c sciebo -n '__fish_sciebo_at verify -' -l only -d 'check only this source' -r
complete -c sciebo -n '__fish_sciebo_at verify -' -l download -d 'download remote files and hash them'
complete -c sciebo -n '__fish_sciebo_at verify -' -l size-only -d 'compare sizes only, skip hashes'
complete -c sciebo -n '__fish_sciebo_at verify -' -l quiet -d 'only print failures and the summary'
complete -c sciebo -n '__fish_sciebo_at status -' -l only -d 'show only this source' -r
complete -c sciebo -n '__fish_sciebo_at status -' -l history -d 'print the last N recorded runs' -r
complete -c sciebo -n '__fish_sciebo_at status -' -l json -d 'print the report as JSON'
complete -c sciebo -n '__fish_sciebo_at status -' -l watch -d 'refresh the report every N seconds' -r
complete -c sciebo -n '__fish_sciebo_at status -' -l quiet -d 'only print rows that need attention'
complete -c sciebo -n '__fish_sciebo_at pause -' -l for -d 'pause for this long' -r
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is folders' -a 'choose add import edit list pause resume remove'
complete -c sciebo -n '__fish_sciebo_at folders choose' -l depth -d 'remote scan depth' -r
complete -c sciebo -n '__fish_sciebo_at folders choose' -l local-root -d 'local root for default destinations' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at folders choose' -l mode -d 'fix the direction for all picks' -r -f -a 'sync pull bisync'
complete -c sciebo -n '__fish_sciebo_at folders choose' -l select -d 'pick which subfolders to sync'
complete -c sciebo -n '__fish_sciebo_at folders choose' -l no-fzf -d 'always use the numbered menu'
complete -c sciebo -n '__fish_sciebo_at folders choose' -l no-dry-run -d 'do not offer a dry run after adding pairs'
complete -c sciebo -n '__fish_sciebo_at folders add' -l remote -d 'remote subfolder below the remote base' -r
complete -c sciebo -n '__fish_sciebo_at folders add' -l local -d 'local path' -r
complete -c sciebo -n '__fish_sciebo_at folders add' -l mode -d 'direction' -r -f -a 'sync pull bisync'
complete -c sciebo -n '__fish_sciebo_at folders add' -l select -d 'interactively pick subfolders to sync'
complete -c sciebo -n '__fish_sciebo_at folders add' -l include -d 'sync only this subfolder below --remote' -r
complete -c sciebo -n '__fish_sciebo_at folders add' -l exclude -d 'exclude this subfolder' -r
complete -c sciebo -n '__fish_sciebo_at folders add' -l local-root -d 'local root for the default destination' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at folders import' -l remote -d 'remote subfolder below the remote base' -r
complete -c sciebo -n '__fish_sciebo_at folders import' -l local -d 'local path' -r
complete -c sciebo -n '__fish_sciebo_at folders import' -l mode -d 'direction' -r -f -a 'sync pull bisync'
complete -c sciebo -n '__fish_sciebo_at folders import' -l local-root -d 'local root for the default destination' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at folders import' -l select -d 'sync only the listed folders'
complete -c sciebo -n '__fish_sciebo_at folders edit' -l local -d 'replace the local folder' -r
complete -c sciebo -n '__fish_sciebo_at folders edit' -l remote -d 'replace the remote subfolder' -r
complete -c sciebo -n '__fish_sciebo_at folders edit' -l force -d 'allow a remote change with stale bisync state'
complete -c sciebo -n '__fish_sciebo_at folders edit' -l include -d 'sync only these immediate subfolders' -r
complete -c sciebo -n '__fish_sciebo_at folders edit' -l exclude -d 'exclude this subfolder' -r
complete -c sciebo -n '__fish_sciebo_at folders edit' -l mode -d 'change the direction' -r -f -a 'sync pull bisync'
complete -c sciebo -n '__fish_sciebo_at folders edit' -l select -d 'interactively pick subfolders to sync'
complete -c sciebo -n '__fish_sciebo_at folders edit' -l clear -d 'remove the pair filter (no rules)'
complete -c sciebo -n '__fish_sciebo_at folders list' -l json -d 'print the pairs as JSON'
complete -c sciebo -n '__fish_sciebo_at folders remove' -l purge -d 'also delete the pair state and filter'
complete -c sciebo -n '__fish_sciebo_at mount -' -l folder -d 'remote subfolder below the remote base' -r
complete -c sciebo -n '__fish_sciebo_at mount -' -l mountpoint -d 'local mountpoint' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at mount -' -l ro -d 'read-only mount, no VFS cache'
complete -c sciebo -n '__fish_sciebo_at mount -' -l foreground -d 'run rclone in the foreground'
complete -c sciebo -n '__fish_sciebo_at mount -' -l sudo -d 'run rclone as root'
complete -c sciebo -n '__fish_sciebo_at umount -' -l folder -d 'unmount the mount for this remote subfolder' -r
complete -c sciebo -n '__fish_sciebo_at umount -' -l mountpoint -d 'unmount the mount for this local mountpoint' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at umount -' -l all -d 'unmount every recorded mount'
complete -c sciebo -n '__fish_sciebo_at umount -' -l sudo -d 'run umount as root'
complete -c sciebo -n '__fish_sciebo_at mounts -' -l folder -d 'only show this remote subfolder' -r
complete -c sciebo -n '__fish_sciebo_at mounts -' -l check -d 'exit 1 when a recorded mount is not visible'
complete -c sciebo -n '__fish_sciebo_at mounts -' -l prune -d 'remove stale mount records'
complete -c sciebo -n '__fish_sciebo_at mounts -' -l json -d 'print the mounts as JSON'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l logs -d 'delete old log files and rotate large ones'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l uploads -d 'delete stale chunk uploads'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l state -d 'delete stale bisync, lock, temp, and mount state'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l junk -d 'delete files matching fleeting.txt'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l cache -d 'delete stale mount-cache files'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l support -d 'keep the newest support archives'
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l keep -d 'archives to keep for --support' -r
complete -c sciebo -n '__fish_sciebo_at cleanup -' -l apply -d 'actually delete (default is a dry run)'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is schedule' -a 'install uninstall status'
complete -c sciebo -n '__fish_sciebo_at schedule install' -l at-login -d 'start the agent at login/boot'
complete -c sciebo -n '__fish_sciebo_at schedule install' -l profiles -d 'render one extra agent per profile' -r
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is trash' -a 'list restore rm empty'
complete -c sciebo -n '__fish_sciebo_at trash restore' -l all -d 'restore every listed item'
complete -c sciebo -n '__fish_sciebo_at trash restore' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at trash rm' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at trash empty' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at versions -' -l download -d 'save this version' -r
complete -c sciebo -n '__fish_sciebo_at versions -' -l output -d 'write the --download body to FILE' -r
complete -c sciebo -n '__fish_sciebo_at versions -' -l stdout -d 'stream the --download body to standard output'
complete -c sciebo -n '__fish_sciebo_at versions -' -l restore -d 'restore this version' -r
complete -c sciebo -n '__fish_sciebo_at versions -' -l delete -d 'delete this version' -r
complete -c sciebo -n '__fish_sciebo_at versions -' -l yes -d 'skip the --restore/--delete confirmation'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is share' -a 'link user group email guest circle talk deck remote list info update remove leave pending accept decline send-email remote-list search copy-link copy-internal incoming'
complete -c sciebo -n '__fish_sciebo_at share link' -l password -d 'protect the link with a password' -r
complete -c sciebo -n '__fish_sciebo_at share link' -l expire -d 'expire the link on this date' -r
complete -c sciebo -n '__fish_sciebo_at share link' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share link' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share link' -l label -d 'set a link label' -r
complete -c sciebo -n '__fish_sciebo_at share link' -l download -d 'allow downloads: 0 hides them' -r -f -a '0 1'
complete -c sciebo -n '__fish_sciebo_at share link' -l file-drop -d 'upload-only link (permission 4)'
complete -c sciebo -n '__fish_sciebo_at share link' -l file-request -d 'mark the link as a file request'
complete -c sciebo -n '__fish_sciebo_at share link' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share user' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share user' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share user' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share user' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share group' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share group' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share group' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share group' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share email' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share email' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share email' -l password -d 'protect the share with a password' -r
complete -c sciebo -n '__fish_sciebo_at share email' -l expire -d 'expire the share on this date' -r
complete -c sciebo -n '__fish_sciebo_at share email' -l send-password-by-talk -d 'share the password through Talk'
complete -c sciebo -n '__fish_sciebo_at share email' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share email' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share guest' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share guest' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share guest' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share guest' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share circle' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share circle' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share circle' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share circle' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share talk' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share talk' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share talk' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share talk' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share deck' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share deck' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share deck' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share deck' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share remote' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share remote' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share remote' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share remote' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share list' -l reshares -d 'ask the server for reshares only'
complete -c sciebo -n '__fish_sciebo_at share list' -l json -d 'print the shares as JSON'
complete -c sciebo -n '__fish_sciebo_at share update' -l password -d 'set the password' -r
complete -c sciebo -n '__fish_sciebo_at share update' -l remove-password -d 'remove the password'
complete -c sciebo -n '__fish_sciebo_at share update' -l expire -d 'set the expiration date' -r
complete -c sciebo -n '__fish_sciebo_at share update' -l remove-expire -d 'remove the expiration date'
complete -c sciebo -n '__fish_sciebo_at share update' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share update' -l remove-note -d 'remove the note'
complete -c sciebo -n '__fish_sciebo_at share update' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share update' -l label -d 'set a link label' -r
complete -c sciebo -n '__fish_sciebo_at share update' -l download -d 'allow downloads: 0 hides them' -r -f -a '0 1'
complete -c sciebo -n '__fish_sciebo_at share update' -l send-mail -d 'ask the server to email the recipient'
complete -c sciebo -n '__fish_sciebo_at share remove' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at share leave' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at share pending' -l local -d 'only local pending shares'
complete -c sciebo -n '__fish_sciebo_at share pending' -l remote -d 'only federated pending shares'
complete -c sciebo -n '__fish_sciebo_at share pending' -l json -d 'print the pending shares as JSON'
complete -c sciebo -n '__fish_sciebo_at share accept' -l remote -d 'force the federated list'
complete -c sciebo -n '__fish_sciebo_at share accept' -l all -d 'accept every pending share'
complete -c sciebo -n '__fish_sciebo_at share decline' -l remote -d 'force the federated list'
complete -c sciebo -n '__fish_sciebo_at share decline' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at share decline' -l all -d 'decline every pending share'
complete -c sciebo -n '__fish_sciebo_at share remote-list' -l json -d 'print the remote shares as JSON'
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l password -d 'protect the link with a password' -r
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l expire -d 'expire the link on this date' -r
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l note -d 'attach a note' -r
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l permissions -d 'permission letters or a numeric mask' -r
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l label -d 'set a link label' -r
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l download -d 'allow downloads: 0 hides them' -r -f -a '0 1'
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l file-drop -d 'upload-only link (permission 4)'
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l file-request -d 'mark the link as a file request'
complete -c sciebo -n '__fish_sciebo_at share copy-link' -l json -d 'print the created share as JSON'
complete -c sciebo -n '__fish_sciebo_at share incoming' -l json -d 'print the shares as JSON'
complete -c sciebo -n '__fish_sciebo_at notifications -' -l limit -d 'print and notify at most N notifications' -r
complete -c sciebo -n '__fish_sciebo_at notifications -' -l app -d 'only notifications from these apps' -r
complete -c sciebo -n '__fish_sciebo_at notifications -' -l type -d 'only notifications with these object types' -r
complete -c sciebo -n '__fish_sciebo_at notifications -' -l unseen -d 'only notifications not yet in the seen cache'
complete -c sciebo -n '__fish_sciebo_at notifications -' -l action -d 'run an action on a notification' -r
complete -c sciebo -n '__fish_sciebo_at notifications -' -l delete -d 'delete one notification' -r
complete -c sciebo -n '__fish_sciebo_at notifications -' -l delete-all -d 'delete every notification'
complete -c sciebo -n '__fish_sciebo_at notifications -' -l notify -d 'send a notification per new notification'
complete -c sciebo -n '__fish_sciebo_at notifications -' -l json -d 'print the filtered notifications as JSON'
complete -c sciebo -n '__fish_sciebo_at notifications -' -l watch -d 'poll every N seconds' -r
complete -c sciebo -n '__fish_sciebo_at notifications -' -l quiet -d 'print no notification rows'
complete -c sciebo -n '__fish_sciebo_at notifications -' -l yes -d 'skip the --delete-all confirmation'
complete -c sciebo -n '__fish_sciebo_at activity -' -l limit -d 'print and notify at most N activities' -r
complete -c sciebo -n '__fish_sciebo_at activity -' -l since -d 'only activities newer than DURATION (paged)' -r
complete -c sciebo -n '__fish_sciebo_at activity -' -l notify -d 'send a notification per new activity'
complete -c sciebo -n '__fish_sciebo_at activity -' -l quiet -d 'print no activity rows'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is presence' -a 'show set clear'
complete -c sciebo -n '__fish_sciebo_at presence set' -l message -d 'publish a custom message' -r
complete -c sciebo -n '__fish_sciebo_at presence set' -l emoji -d 'publish a status emoji' -r
complete -c sciebo -n '__fish_sciebo_at presence set' -l clear-after -d 'expire the message after' -r
complete -c sciebo -n '__fish_sciebo_at presence set' -f -a 'online away dnd offline'
complete -c sciebo -n '__fish_sciebo_at unlock -' -l all -d 'release every recorded lock'
complete -c sciebo -n '__fish_sciebo_at unlock -' -l yes -d 'skip the --all confirmation'
complete -c sciebo -n '__fish_sciebo_at locks -' -l prune -d 'forget records whose lock-token is gone'
complete -c sciebo -n '__fish_sciebo_at locks -' -l unlock-all -d 'release every recorded lock'
complete -c sciebo -n '__fish_sciebo_at locks -' -l yes -d 'skip the --unlock-all confirmation'
complete -c sciebo -n '__fish_sciebo_at quota -' -l json -d 'print rclone JSON output'
complete -c sciebo -n '__fish_sciebo_at open -' -l print -d 'print the resolved path or URL instead of opening it'
complete -c sciebo -n '__fish_sciebo_at open -' -l web -d 'open the folder in the Nextcloud web UI'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l resolve -d 'resolve conflict files instead of listing' -r -f -a 'keep-local keep-remote keep-newest keep-oldest keep-both'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l only -d 'scan or resolve only this source' -r
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l kind -d 'scan or resolve only one conflict kind' -r -f -a 'copy case all'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l remote -d 'list case clashes on the server instead of local files'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l open -d 'open the conflict directories with the platform opener'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l apply -d 'carry out the planned actions'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l yes -d 'skip the --apply confirmation'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l json -d 'print the resolve result as JSON'
complete -c sciebo -n '__fish_sciebo_at conflicts -' -l quiet -d 'print nothing; exit 1 when conflict files exist'
complete -c sciebo -n '__fish_sciebo_at retry -' -l list -d 'show all blacklist records and exit'
complete -c sciebo -n '__fish_sciebo_at retry -' -l all -d 'clear every source records'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is account' -a 'list add import remove use info avatar status'
complete -c sciebo -n '__fish_sciebo_at account add' -l remote -d 'rclone remote name' -r
complete -c sciebo -n '__fish_sciebo_at account add' -l base -d 'remote base folder' -r
complete -c sciebo -n '__fish_sciebo_at account import' -l nextcloud-cfg -d 'read FILE instead of the default nextcloud.cfg' -r
complete -c sciebo -n '__fish_sciebo_at account import' -l profile -d 'import only the matching account' -r
complete -c sciebo -n '__fish_sciebo_at account import' -l dry-run -d 'print the plan and write nothing'
complete -c sciebo -n '__fish_sciebo_at account import' -l yes -d 'merge without asking'
complete -c sciebo -n '__fish_sciebo_at account import' -l json -d 'print the plan as JSON'
complete -c sciebo -n '__fish_sciebo_at account remove' -l yes -d 'skip the confirmation'
complete -c sciebo -n '__fish_sciebo_at account remove' -f -a '(__fish_sciebo_profiles)'
complete -c sciebo -n '__fish_sciebo_at account use' -f -a '(__fish_sciebo_profiles)'
complete -c sciebo -n '__fish_sciebo_at account info' -l json -d 'print the account info as JSON'
complete -c sciebo -n '__fish_sciebo_at account avatar' -l output -d 'write the avatar to FILE' -r
complete -c sciebo -n '__fish_sciebo_at account avatar' -l size -d 'avatar pixel size' -r
complete -c sciebo -n '__fish_sciebo_at account status' -l json -d 'print the status as JSON'
complete -c sciebo -n '__fish_sciebo_at logout -' -l revoke -d 'revoke the app password on the server first'
complete -c sciebo -n '__fish_sciebo_at logout -' -l yes -d 'do not ask for confirmation'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is config' -a 'list get check edit'
complete -c sciebo -n '__fish_sciebo_at config list' -l json -d 'print the result as JSON'
complete -c sciebo -n '__fish_sciebo_at config list' -l all -d 'also show settings whose value is empty'
complete -c sciebo -n '__fish_sciebo_at config get' -l json -d 'print the result as JSON'
complete -c sciebo -n '__fish_sciebo_at config check' -l json -d 'print the result as JSON'
complete -c sciebo -n '__fish_sciebo_at support -' -l output -d 'archive path' -r
complete -c sciebo -n '__fish_sciebo_at support -' -l no-network -d 'accepted for compatibility; doctor runs offline'
complete -c sciebo -n '__fish_sciebo_at support -' -l json -d 'print the archive summary as JSON'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l path -d 'remote folder below the user root' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l confdir -d 'configuration base for this run' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s u -l user -d 'user name' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s p -l password -d 'password' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l password-fd -d 'read the password from an already-open file descriptor' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s n -d 'read credentials from ~/.netrc'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s s -l silent -d 'errors only'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l httpproxy -d 'HTTP proxy URL' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l exclude -d 'read exclude patterns from FILE' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l exclude-anchored -d 'read sync-root patterns from FILE' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l unsyncedfolders -d 'exclude every folder listed in FILE' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l max-sync-retries -d 'retry the whole sync up to N times' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l uplimit -d 'upload bandwidth cap' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l downlimit -d 'download bandwidth cap' -r
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l logdebug -d 'debug-level logging'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l verbose -d 'debug-level logging'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s P -l progress -d 'show rclone transfer progress (terminal only)'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s v -l version -d 'print the version and exit'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -s h -d 'sync hidden files'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -l dry-run -d 'report what would change, change nothing'
complete -c sciebo -n '__fish_sciebo_at nextcloudcmd -' -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at watch -' -l interval -d 'poll interval in seconds' -r
complete -c sciebo -n '__fish_sciebo_at watch -' -l debounce -d 'coalesce change events for N seconds' -r
complete -c sciebo -n '__fish_sciebo_at watch -' -l only -d 'watch only this source' -r
complete -c sciebo -n '__fish_sciebo_at watch -' -l remote-interval -d 'check the remote every N seconds' -r
complete -c sciebo -n '__fish_sciebo_at watch -' -l backend -d 'change-detection backend' -r -f -a 'auto fswatch inotify poll'
complete -c sciebo -n '__fish_sciebo_at watch -' -l once -d 'run one detection cycle and exit'
complete -c sciebo -n '__fish_sciebo_at watch -' -l notify -d 'allow desktop notifications'
complete -c sciebo -n '__fish_sciebo_at watch -' -l no-notify -d 'disable desktop notifications even when NOTIFY=1'
complete -c sciebo -n '__fish_sciebo_at watch -' -l quiet -d 'only warnings and errors'
complete -c sciebo -n '__fish_sciebo_at limit -' -l up -d 'upload cap, e.g. 2M' -r
complete -c sciebo -n '__fish_sciebo_at limit -' -l down -d 'download cap, e.g. 5M' -r
complete -c sciebo -n '__fish_sciebo_at limit -' -l until -d 'expire after this long' -r
complete -c sciebo -n '__fish_sciebo_at limit -' -l show -d 'print the current limit'
complete -c sciebo -n '__fish_sciebo_at limit -' -l clear -d 'remove the marker'
complete -c sciebo -n '__fish_sciebo_at limit -' -l json -d 'print the state as JSON'
complete -c sciebo -n '__fish_sciebo_at network -' -l json -d 'print the state as JSON'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is filters' -a 'sync list show check'
complete -c sciebo -n '__fish_sciebo_at filters sync' -l json -d 'print the result as JSON'
complete -c sciebo -n '__fish_sciebo_at filters list' -l json -d 'print the result as JSON'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is file' -a 'info activity shares'
complete -c sciebo -n '__fish_sciebo_at file info' -l json -d 'print the metadata as JSON'
complete -c sciebo -n '__fish_sciebo_at file activity' -l limit -d 'print at most N entries' -r
complete -c sciebo -n '__fish_sciebo_at file activity' -l json -d 'print the activity as JSON'
complete -c sciebo -n '__fish_sciebo_at file shares' -l json -d 'print the shares as JSON'
complete -c sciebo -n '__fish_sciebo_at search -' -l limit -d 'ask the server for at most N results' -r
complete -c sciebo -n '__fish_sciebo_at search -' -l json -d 'print the results as JSON'
complete -c sciebo -n '__fish_sciebo_at search -' -l open -d 'open the first result with the platform opener'
complete -c sciebo -n '__fish_sciebo_at recent -' -l since -d 'only files modified within DURATION' -r
complete -c sciebo -n '__fish_sciebo_at recent -' -l limit -d 'print at most N files' -r
complete -c sciebo -n '__fish_sciebo_at recent -' -l json -d 'print the files as JSON'
complete -c sciebo -n '__fish_sciebo_at comments -' -l limit -d 'list at most N comments' -r
complete -c sciebo -n '__fish_sciebo_at comments -' -l json -d 'print the listing as JSON'
complete -c sciebo -n '__fish_sciebo_at comments -' -l yes -d 'skip the delete confirmation'
complete -c sciebo -n '__fish_sciebo_at comments -' -f -a 'list add delete'
complete -c sciebo -n '__fish_sciebo_at favorites -' -l json -d 'print the listing as JSON'
complete -c sciebo -n '__fish_sciebo_at favorites -' -f -a 'list add remove'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is tags' -a 'list create assign clear'
complete -c sciebo -n '__fish_sciebo_at tags list' -l json -d 'print the listing as JSON'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is server' -a 'info capabilities status'
complete -c sciebo -n '__fish_sciebo_at server info' -l json -d 'print a JSON document'
complete -c sciebo -n '__fish_sciebo_at server capabilities' -l raw -d 'print the cached raw OCS response'
complete -c sciebo -n '__fish_sciebo_at server capabilities' -l json -d 'print the capabilities as JSON'
complete -c sciebo -n '__fish_sciebo_at hydrate -' -l dest -d 'copy into DIR instead of the resolved destination' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at hydrate -' -l dry-run -d 'report what would be copied; changes nothing'
complete -c sciebo -n '__fish_sciebo_at hydrate -' -l quiet -d 'do not print the success line'
complete -c sciebo -n '__fish_sciebo_at hydrate -' -l json -d 'print the result as JSON'
complete -c sciebo -n '__fish_sciebo_at hydrate -' -l progress -d 'show rclone transfer progress (terminal only)'
complete -c sciebo -n '__fish_sciebo_at provision -' -l userid -d 'Nextcloud user id' -r
complete -c sciebo -n '__fish_sciebo_at provision -' -l apppassword -d 'app password' -r
complete -c sciebo -n '__fish_sciebo_at provision -' -l apppassword-fd -d 'read the app password from this open file descriptor' -r
complete -c sciebo -n '__fish_sciebo_at provision -' -l serverurl -d 'server base URL' -r
complete -c sciebo -n '__fish_sciebo_at provision -' -l localdirpath -d 'local folder to pair' -r -f -a '(__fish_complete_directories)'
complete -c sciebo -n '__fish_sciebo_at provision -' -l remotedirpath -d 'remote folder below the remote base' -r
complete -c sciebo -n '__fish_sciebo_at provision -' -l isvfsenabled -d 'desktop compatibility flag; 1 warns and is ignored' -r -f -a '0 1'
complete -c sciebo -n '__fish_sciebo_at provision -' -l profile -d 'profile to create or update' -r -f -a '(__fish_sciebo_profiles)'
complete -c sciebo -f -n '__fish_sciebo_needs_sub; and __fish_sciebo_cmd_is logs' -a 'list show tail path'
complete -c sciebo -n '__fish_sciebo_at logs list' -l json -d 'print the rows as JSON'
complete -c sciebo -n '__fish_sciebo_at logs show' -l lines -d 'trailing lines to print' -r
complete -c sciebo -n '__fish_sciebo_at logs tail' -l lines -d 'trailing lines to print' -r
complete -c sciebo -n '__fish_sciebo_at edit -' -l editor -d 'editor command, possibly with arguments' -r
complete -c sciebo -n '__fish_sciebo_at edit -' -l no-upload -d 'do not upload after editing'
complete -c sciebo -n '__fish_sciebo_at edit -' -l lock -d 'take a WebDAV lock while editing'
complete -c sciebo -n '__fish_sciebo_at ignored -' -l source -d 'restrict the scan to one source' -r
complete -c sciebo -n '__fish_sciebo_at ignored -' -l json -d 'print the ignored files as JSON'
complete -c sciebo -n '__fish_sciebo_at announcements -' -l limit -d 'print at most N announcements' -r
complete -c sciebo -n '__fish_sciebo_at announcements -' -l no-dismiss -d 'accepted for compatibility'
complete -c sciebo -n '__fish_sciebo_at announcements -' -l json -d 'print the announcements as JSON'
complete -c sciebo -n '__fish_sciebo_at preview -' -l output -d 'write the image to FILE' -r
complete -c sciebo -n '__fish_sciebo_at preview -' -l size -d 'preview edge size in pixels' -r
complete -c sciebo -n '__fish_sciebo_at download -' -l dry-run -d 'report what would be transferred; change nothing'
complete -c sciebo -n '__fish_sciebo_at download -' -l force -d 'download even when the destination matches'
complete -c sciebo -n '__fish_sciebo_at download -' -l resume -d 'continue a partial file'
complete -c sciebo -n '__fish_sciebo_at download -' -l continue -d 'continue a partial file'
complete -c sciebo -n '__fish_sciebo_at download -' -l quiet -d 'do not print the success line'
complete -c sciebo -n '__fish_sciebo_at download -' -l json -d 'print a structured summary'
complete -c sciebo -n '__fish_sciebo_at download -' -l progress -d 'show rclone transfer progress (terminal only)'
complete -c sciebo -n '__fish_sciebo_at update -' -l check -d 'only report the local vs upstream state'
complete -c sciebo -n '__fish_sciebo_at update -' -l json -d 'print the report as JSON'
complete -c sciebo -n '__fish_sciebo_at help -' -f -a '(__fish_sciebo_commands)'

