# Generated by scripts/gen-completions.sh from completions/sciebo.spec; do not edit.
#
# bash completion for the sciebo CLI. Install: source this file from a
# bash-completion drop-in, or copy it into a completions directory (for
# example ~/.local/share/bash-completion/completions/sciebo).

_sciebo_commands='setup doctor discover list check sync verify status pause resume folders mount umount mounts cleanup schedule trash versions share notifications activity presence lock unlock locks quota open conflicts retry account logout config support nextcloudcmd watch limit unlimited network filters file search recent comments favorites tags server hydrate provision logs edit ignored announcements preview download update help'
_sciebo_dispatch_commands='folders schedule trash share presence account config filters file tags server logs'
_sciebo_global_opts='-h --help --profile --trust --non-interactive --debug --log-file --confdir --log-dir --log-expire --version -V'

_sciebo_compgen() {
  local cur="$1"
  shift
  # shellcheck disable=SC2207  # word-splitting the completion list is intended
  COMPREPLY=($(compgen -W "$*" -- "$cur"))
}

_sciebo_filedir() {
  local cur="$1"
  if declare -F _filedir >/dev/null 2>&1; then
    _filedir
  else
    # shellcheck disable=SC2207  # word-splitting the file list is intended
    COMPREPLY=($(compgen -f -- "$cur"))
  fi
}

_sciebo_dirs() {
  local cur="$1"
  if declare -F _filedir >/dev/null 2>&1; then
    _filedir -d
  else
    # shellcheck disable=SC2207  # word-splitting the directory list is intended
    COMPREPLY=($(compgen -d -- "$cur"))
  fi
}

_sciebo_project_root() {
  local src="${BASH_SOURCE[0]}" dir
  case "$src" in
    */*) ;;
    *) src="./$src" ;;
  esac
  dir="$(cd "${src%/*}" 2>/dev/null && pwd)" || return 0
  dir="${dir%/*}"
  [[ -n "$dir" ]] || dir="/"
  [[ -d "${dir}/config" ]] && printf '%s' "$dir"
}

_sciebo_profile_names() {
  local root name base
  root="$(_sciebo_project_root)"
  if [[ -n "$root" && -d "${root}/config/profiles" ]]; then
    for name in "${root}/config/profiles"/*/; do
      [[ -d "$name" ]] || continue
      base="${name%/}"
      printf '%s\n' "${base##*/}"
    done
  fi
  printf 'default\n'
}

_sciebo_profiles() {
  local cur="$1" names
  names="$(_sciebo_profile_names)"
  _sciebo_compgen "$cur" "$names"
}

_sciebo_is_dispatch() {
  case " $_sciebo_dispatch_commands " in
    *" $1 "*) return 0 ;;
  esac
  return 1
}

# _sciebo_complete_action ACTION CUR - dispatch a value/positional ACTION
# (none/files/dirs/profiles/commands/enum:a,b,c) against CUR.
_sciebo_complete_action() {
  local action="$1" cur="$2" list
  case "$action" in
    files) _sciebo_filedir "$cur" ;;
    dirs) _sciebo_dirs "$cur" ;;
    profiles) _sciebo_profiles "$cur" ;;
    commands) _sciebo_compgen "$cur" "$_sciebo_commands" ;;
    enum:*)
      list="${action#enum:}"
      _sciebo_compgen "$cur" "${list//,/ }"
      ;;
    *) COMPREPLY=() ;;
  esac
}

_sciebo_subs_for() {
  case "$1" in
    'folders') printf '%s\n' 'choose add import edit list pause resume remove' ;;
    'schedule') printf '%s\n' 'install uninstall status' ;;
    'trash') printf '%s\n' 'list restore rm empty' ;;
    'share') printf '%s\n' 'link user group email guest circle talk deck remote list info update remove leave pending accept decline send-email remote-list search copy-link copy-internal incoming' ;;
    'presence') printf '%s\n' 'show set clear' ;;
    'account') printf '%s\n' 'list add import remove use info avatar status' ;;
    'config') printf '%s\n' 'list get check edit' ;;
    'filters') printf '%s\n' 'sync list show check' ;;
    'file') printf '%s\n' 'info activity shares' ;;
    'tags') printf '%s\n' 'list create assign clear' ;;
    'server') printf '%s\n' 'info capabilities status' ;;
    'logs') printf '%s\n' 'list show tail path' ;;
    *) printf '\n' ;;
  esac
}

_sciebo_options_for() {
  local cmd="$1" sub="$2"
  case "$cmd:$sub" in
    'setup:-') printf '%s\n' '--login --url --rotate --no-keychain --proxy --crypt' ;;
    'doctor:-') printf '%s\n' '--offline --json' ;;
    'discover:-') printf '%s\n' '--write' ;;
    'list:-') printf '%s\n' '--json' ;;
    'check:-') printf '%s\n' '--apply --dry-run --only --list --resync --yes --metered-ok --quiet --no-lock --force' ;;
    'sync:-') printf '%s\n' '--apply --dry-run --only --list --resync --yes --metered-ok --quiet --no-lock --force' ;;
    'verify:-') printf '%s\n' '--only --download --size-only --quiet' ;;
    'status:-') printf '%s\n' '--only --history --json --watch --quiet' ;;
    'pause:-') printf '%s\n' '--for' ;;
    'folders:choose') printf '%s\n' '--depth --local-root --mode --select --no-fzf --no-dry-run' ;;
    'folders:add') printf '%s\n' '--remote --local --mode --select --include --exclude --local-root' ;;
    'folders:import') printf '%s\n' '--remote --local --mode --local-root --select' ;;
    'folders:edit') printf '%s\n' '--local --remote --force --include --exclude --mode --select --clear' ;;
    'folders:list') printf '%s\n' '--json' ;;
    'folders:remove') printf '%s\n' '--purge' ;;
    'mount:-') printf '%s\n' '--folder --mountpoint --ro --foreground --sudo' ;;
    'umount:-') printf '%s\n' '--folder --mountpoint --all --sudo' ;;
    'mounts:-') printf '%s\n' '--folder --check --prune --json' ;;
    'cleanup:-') printf '%s\n' '--logs --uploads --state --junk --cache --support --keep --apply' ;;
    'schedule:install') printf '%s\n' '--at-login --profiles' ;;
    'trash:restore') printf '%s\n' '--all --yes' ;;
    'trash:rm') printf '%s\n' '--yes' ;;
    'trash:empty') printf '%s\n' '--yes' ;;
    'versions:-') printf '%s\n' '--download --output --stdout --restore --delete --yes' ;;
    'share:link') printf '%s\n' '--password --expire --note --permissions --label --download --file-drop --file-request --json' ;;
    'share:copy-link') printf '%s\n' '--password --expire --note --permissions --label --download --file-drop --file-request --json' ;;
    'share:user') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:group') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:guest') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:circle') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:talk') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:deck') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:remote') printf '%s\n' '--permissions --note --send-mail --json' ;;
    'share:email') printf '%s\n' '--permissions --note --password --expire --send-password-by-talk --send-mail --json' ;;
    'share:list') printf '%s\n' '--reshares --json' ;;
    'share:update') printf '%s\n' '--password --remove-password --expire --remove-expire --note --remove-note --permissions --label --download --send-mail' ;;
    'share:remove') printf '%s\n' '--yes' ;;
    'share:leave') printf '%s\n' '--yes' ;;
    'share:pending') printf '%s\n' '--local --remote --json' ;;
    'share:accept') printf '%s\n' '--remote --all' ;;
    'share:decline') printf '%s\n' '--remote --yes --all' ;;
    'share:remote-list') printf '%s\n' '--json' ;;
    'share:incoming') printf '%s\n' '--json' ;;
    'notifications:-') printf '%s\n' '--limit --app --type --unseen --action --delete --delete-all --notify --json --watch --quiet --yes' ;;
    'activity:-') printf '%s\n' '--limit --since --notify --quiet' ;;
    'presence:set') printf '%s\n' '--message --emoji --clear-after' ;;
    'unlock:-') printf '%s\n' '--all --yes' ;;
    'locks:-') printf '%s\n' '--prune --unlock-all --yes' ;;
    'quota:-') printf '%s\n' '--json' ;;
    'open:-') printf '%s\n' '--print --web' ;;
    'conflicts:-') printf '%s\n' '--resolve --only --kind --remote --open --apply --yes --json --quiet' ;;
    'retry:-') printf '%s\n' '--list --all' ;;
    'account:add') printf '%s\n' '--remote --base' ;;
    'account:import') printf '%s\n' '--nextcloud-cfg --profile --dry-run --yes --json' ;;
    'account:remove') printf '%s\n' '--yes' ;;
    'account:info') printf '%s\n' '--json' ;;
    'account:avatar') printf '%s\n' '--output --size' ;;
    'account:status') printf '%s\n' '--json' ;;
    'logout:-') printf '%s\n' '--revoke --yes' ;;
    'config:list') printf '%s\n' '--json --all' ;;
    'config:get') printf '%s\n' '--json' ;;
    'config:check') printf '%s\n' '--json' ;;
    'support:-') printf '%s\n' '--output --no-network --json' ;;
    'nextcloudcmd:-') printf '%s\n' '--path --confdir --user -u --password -p --password-fd -n --silent -s --httpproxy --exclude --exclude-anchored --unsyncedfolders --max-sync-retries --uplimit --downlimit --logdebug --verbose --progress -P -v --version -h --dry-run' ;;
    'watch:-') printf '%s\n' '--interval --debounce --only --remote-interval --backend --once --notify --no-notify --quiet' ;;
    'limit:-') printf '%s\n' '--up --down --until --show --clear --json' ;;
    'network:-') printf '%s\n' '--json' ;;
    'filters:sync') printf '%s\n' '--json' ;;
    'filters:list') printf '%s\n' '--json' ;;
    'file:info') printf '%s\n' '--json' ;;
    'file:activity') printf '%s\n' '--limit --json' ;;
    'file:shares') printf '%s\n' '--json' ;;
    'search:-') printf '%s\n' '--limit --json --open' ;;
    'recent:-') printf '%s\n' '--since --limit --json' ;;
    'comments:-') printf '%s\n' '--limit --json --yes' ;;
    'favorites:-') printf '%s\n' '--json' ;;
    'tags:list') printf '%s\n' '--json' ;;
    'server:info') printf '%s\n' '--json' ;;
    'server:capabilities') printf '%s\n' '--raw --json' ;;
    'hydrate:-') printf '%s\n' '--dest --dry-run --quiet --json --progress' ;;
    'provision:-') printf '%s\n' '--userid --apppassword --apppassword-fd --serverurl --localdirpath --remotedirpath --isvfsenabled --profile' ;;
    'logs:-') printf '%s\n' '--json' ;;
    'logs:list') printf '%s\n' '--json' ;;
    'logs:show') printf '%s\n' '--lines' ;;
    'logs:tail') printf '%s\n' '--lines' ;;
    'edit:-') printf '%s\n' '--editor --no-upload --lock' ;;
    'ignored:-') printf '%s\n' '--source --json' ;;
    'announcements:-') printf '%s\n' '--limit --no-dismiss --json' ;;
    'preview:-') printf '%s\n' '--output --size' ;;
    'download:-') printf '%s\n' '--dry-run --force --resume --continue --quiet --json --progress' ;;
    'update:-') printf '%s\n' '--check --json' ;;
    *) printf '\n' ;;
  esac
}

_sciebo_opt_lookup() {
  local cmd="$1" sub="$2" flag="$3"
  _SCIEBO_OPT_KIND=""
  _SCIEBO_OPT_ACTION=""
  case "$cmd:$sub:$flag" in
    'setup:-:--login') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'setup:-:--url') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'setup:-:--rotate') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'setup:-:--no-keychain') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'setup:-:--proxy') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'setup:-:--crypt') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'doctor:-:--offline') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'doctor:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'discover:-:--write') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'list:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--apply') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--only') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--list') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--resync') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--metered-ok') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--no-lock') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'check:-:--force') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--apply') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--only') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--list') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--resync') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--metered-ok') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--no-lock') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'sync:-:--force') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'verify:-:--only') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'verify:-:--download') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'verify:-:--size-only') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'verify:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'status:-:--only') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'status:-:--history') _SCIEBO_OPT_KIND=optional-value; _SCIEBO_OPT_ACTION=none ;;
    'status:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'status:-:--watch') _SCIEBO_OPT_KIND=optional-value; _SCIEBO_OPT_ACTION=none ;;
    'status:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'pause:-:--for') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'folders:choose:--depth') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'folders:choose:--local-root') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'folders:choose:--mode') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:sync,pull,bisync ;;
    'folders:choose:--select') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:choose:--no-fzf') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:choose:--no-dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:add:--remote') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'folders:add:--local') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'folders:add:--mode') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:sync,pull,bisync ;;
    'folders:add:--select') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:add:--include') _SCIEBO_OPT_KIND=repeatable; _SCIEBO_OPT_ACTION=none ;;
    'folders:add:--exclude') _SCIEBO_OPT_KIND=repeatable; _SCIEBO_OPT_ACTION=none ;;
    'folders:add:--local-root') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'folders:import:--remote') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'folders:import:--local') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'folders:import:--mode') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:sync,pull,bisync ;;
    'folders:import:--local-root') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'folders:import:--select') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:edit:--local') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'folders:edit:--remote') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'folders:edit:--force') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:edit:--include') _SCIEBO_OPT_KIND=repeatable; _SCIEBO_OPT_ACTION=none ;;
    'folders:edit:--exclude') _SCIEBO_OPT_KIND=repeatable; _SCIEBO_OPT_ACTION=none ;;
    'folders:edit:--mode') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:sync,pull,bisync ;;
    'folders:edit:--select') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:edit:--clear') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'folders:remove:--purge') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'mount:-:--folder') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'mount:-:--mountpoint') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'mount:-:--ro') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'mount:-:--foreground') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'mount:-:--sudo') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'umount:-:--folder') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'umount:-:--mountpoint') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'umount:-:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'umount:-:--sudo') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'mounts:-:--folder') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'mounts:-:--check') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'mounts:-:--prune') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'mounts:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--logs') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--uploads') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--state') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--junk') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--cache') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--support') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--keep') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'cleanup:-:--apply') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'schedule:install:--at-login') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'schedule:install:--profiles') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'trash:restore:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'trash:restore:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'trash:rm:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'trash:empty:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'versions:-:--download') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'versions:-:--output') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'versions:-:--stdout') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'versions:-:--restore') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'versions:-:--delete') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'versions:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--password') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--expire') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--label') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--download') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:0,1 ;;
    'share:link:--file-drop') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--file-request') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:link:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--password') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--expire') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--label') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--download') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:0,1 ;;
    'share:copy-link:--file-drop') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--file-request') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:copy-link:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:user:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:user:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:user:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:user:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:group:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:group:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:group:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:group:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:guest:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:guest:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:guest:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:guest:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:circle:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:circle:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:circle:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:circle:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:talk:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:talk:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:talk:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:talk:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:deck:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:deck:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:deck:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:deck:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:remote:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:remote:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:remote:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:remote:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--password') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--expire') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--send-password-by-talk') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:email:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:list:--reshares') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--password') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--remove-password') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--expire') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--remove-expire') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--note') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--remove-note') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--permissions') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--label') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'share:update:--download') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:0,1 ;;
    'share:update:--send-mail') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:remove:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:leave:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:pending:--local') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:pending:--remote') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:pending:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:accept:--remote') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:accept:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:decline:--remote') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:decline:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:decline:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:remote-list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'share:incoming:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--app') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--type') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--unseen') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--action') _SCIEBO_OPT_KIND=two-arg; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--delete') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--delete-all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--notify') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--watch') _SCIEBO_OPT_KIND=optional-value; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'notifications:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'activity:-:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'activity:-:--since') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'activity:-:--notify') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'activity:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'presence:set:--message') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'presence:set:--emoji') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'presence:set:--clear-after') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'unlock:-:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'unlock:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'locks:-:--prune') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'locks:-:--unlock-all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'locks:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'quota:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'open:-:--print') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'open:-:--web') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--resolve') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:keep-local,keep-remote,keep-newest,keep-oldest,keep-both ;;
    'conflicts:-:--only') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--kind') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:copy,case,all ;;
    'conflicts:-:--remote') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--open') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--apply') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'conflicts:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'retry:-:--list') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'retry:-:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'account:add:--remote') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'account:add:--base') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'account:import:--nextcloud-cfg') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'account:import:--profile') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'account:import:--dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'account:import:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'account:import:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'account:remove:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'account:info:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'account:avatar:--output') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'account:avatar:--size') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'account:status:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'logout:-:--revoke') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'logout:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'config:list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'config:list:--all') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'config:get:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'config:check:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'support:-:--output') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'support:-:--no-network') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'support:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--path') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--confdir') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'nextcloudcmd:-:--user') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-u') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--password') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-p') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--password-fd') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-n') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--silent') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-s') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--httpproxy') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--exclude') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'nextcloudcmd:-:--exclude-anchored') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'nextcloudcmd:-:--unsyncedfolders') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'nextcloudcmd:-:--max-sync-retries') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--uplimit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--downlimit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--logdebug') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--verbose') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--progress') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-P') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-v') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--version') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:-h') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'nextcloudcmd:-:--dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--interval') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--debounce') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--only') _SCIEBO_OPT_KIND=repeatable; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--remote-interval') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--backend') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:auto,fswatch,inotify,poll ;;
    'watch:-:--once') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--notify') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--no-notify') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'watch:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'limit:-:--up') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'limit:-:--down') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'limit:-:--until') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'limit:-:--show') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'limit:-:--clear') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'limit:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'network:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'filters:sync:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'filters:list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'file:info:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'file:activity:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'file:activity:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'file:shares:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'search:-:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'search:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'search:-:--open') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'recent:-:--since') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'recent:-:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'recent:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'comments:-:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'comments:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'comments:-:--yes') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'favorites:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'tags:list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'server:info:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'server:capabilities:--raw') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'server:capabilities:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'hydrate:-:--dest') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'hydrate:-:--dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'hydrate:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'hydrate:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'hydrate:-:--progress') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'provision:-:--userid') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'provision:-:--apppassword') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'provision:-:--apppassword-fd') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'provision:-:--serverurl') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'provision:-:--localdirpath') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
    'provision:-:--remotedirpath') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'provision:-:--isvfsenabled') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=enum:0,1 ;;
    'provision:-:--profile') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=profiles ;;
    'logs:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'logs:list:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'logs:show:--lines') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'logs:tail:--lines') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'edit:-:--editor') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'edit:-:--no-upload') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'edit:-:--lock') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'ignored:-:--source') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'ignored:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'announcements:-:--limit') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'announcements:-:--no-dismiss') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'announcements:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'preview:-:--output') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
    'preview:-:--size') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--dry-run') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--force') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--resume') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--continue') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--quiet') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'download:-:--progress') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'update:-:--check') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    'update:-:--json') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
  esac
  if [ -z "$_SCIEBO_OPT_KIND" ]; then
    case "$flag" in
      '-h') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
      '--help') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
      '--profile') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=profiles ;;
      '--trust') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
      '--non-interactive') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
      '--debug') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
      '--log-file') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=files ;;
      '--confdir') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
      '--log-dir') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=dirs ;;
      '--log-expire') _SCIEBO_OPT_KIND=value; _SCIEBO_OPT_ACTION=none ;;
      '--version') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
      '-V') _SCIEBO_OPT_KIND=flag; _SCIEBO_OPT_ACTION=none ;;
    esac
  fi
}

_sciebo_pos_action() {
  local cmd="$1" sub="$2" pos="$3"
  _SCIEBO_POS_ACTION=""
  case "$cmd:$sub:$pos" in
    'folders:import:0') _SCIEBO_POS_ACTION=files ;;
    'folders:edit:0') _SCIEBO_POS_ACTION=none ;;
    'folders:pause:0') _SCIEBO_POS_ACTION=none ;;
    'folders:resume:0') _SCIEBO_POS_ACTION=none ;;
    'folders:remove:0') _SCIEBO_POS_ACTION=none ;;
    'versions:-:0') _SCIEBO_POS_ACTION=none ;;
    'share:link:0') _SCIEBO_POS_ACTION=none ;;
    'share:copy-link:0') _SCIEBO_POS_ACTION=none ;;
    'share:user:0') _SCIEBO_POS_ACTION=none ;;
    'share:user:1') _SCIEBO_POS_ACTION=none ;;
    'share:group:0') _SCIEBO_POS_ACTION=none ;;
    'share:group:1') _SCIEBO_POS_ACTION=none ;;
    'share:guest:0') _SCIEBO_POS_ACTION=none ;;
    'share:guest:1') _SCIEBO_POS_ACTION=none ;;
    'share:circle:0') _SCIEBO_POS_ACTION=none ;;
    'share:circle:1') _SCIEBO_POS_ACTION=none ;;
    'share:talk:0') _SCIEBO_POS_ACTION=none ;;
    'share:talk:1') _SCIEBO_POS_ACTION=none ;;
    'share:deck:0') _SCIEBO_POS_ACTION=none ;;
    'share:deck:1') _SCIEBO_POS_ACTION=none ;;
    'share:remote:0') _SCIEBO_POS_ACTION=none ;;
    'share:remote:1') _SCIEBO_POS_ACTION=none ;;
    'share:email:0') _SCIEBO_POS_ACTION=none ;;
    'share:email:1') _SCIEBO_POS_ACTION=none ;;
    'share:list:0') _SCIEBO_POS_ACTION=none ;;
    'share:info:0') _SCIEBO_POS_ACTION=none ;;
    'share:update:0') _SCIEBO_POS_ACTION=none ;;
    'share:remove:0') _SCIEBO_POS_ACTION=none ;;
    'share:leave:0') _SCIEBO_POS_ACTION=none ;;
    'share:accept:0') _SCIEBO_POS_ACTION=none ;;
    'share:decline:0') _SCIEBO_POS_ACTION=none ;;
    'share:send-email:0') _SCIEBO_POS_ACTION=none ;;
    'share:search:0') _SCIEBO_POS_ACTION=none ;;
    'share:copy-internal:0') _SCIEBO_POS_ACTION=none ;;
    'presence:set:0') _SCIEBO_POS_ACTION=enum:online,away,dnd,offline ;;
    'lock:-:0') _SCIEBO_POS_ACTION=none ;;
    'unlock:-:0') _SCIEBO_POS_ACTION=none ;;
    'open:-:0') _SCIEBO_POS_ACTION=files ;;
    'retry:-:0') _SCIEBO_POS_ACTION=none ;;
    'retry:-:1') _SCIEBO_POS_ACTION=none ;;
    'account:add:0') _SCIEBO_POS_ACTION=none ;;
    'account:remove:0') _SCIEBO_POS_ACTION=profiles ;;
    'account:use:0') _SCIEBO_POS_ACTION=profiles ;;
    'config:get:0') _SCIEBO_POS_ACTION=none ;;
    'nextcloudcmd:-:0') _SCIEBO_POS_ACTION=dirs ;;
    'nextcloudcmd:-:1') _SCIEBO_POS_ACTION=none ;;
    'filters:show:0') _SCIEBO_POS_ACTION=none ;;
    'file:info:0') _SCIEBO_POS_ACTION=none ;;
    'file:activity:0') _SCIEBO_POS_ACTION=none ;;
    'file:shares:0') _SCIEBO_POS_ACTION=none ;;
    'search:-:0') _SCIEBO_POS_ACTION=none ;;
    'comments:-:0') _SCIEBO_POS_ACTION=none ;;
    'comments:-:1') _SCIEBO_POS_ACTION=enum:list,add,delete ;;
    'comments:-:2') _SCIEBO_POS_ACTION=none ;;
    'favorites:-:0') _SCIEBO_POS_ACTION=enum:list,add,remove ;;
    'favorites:-:1') _SCIEBO_POS_ACTION=none ;;
    'tags:create:0') _SCIEBO_POS_ACTION=none ;;
    'tags:assign:0') _SCIEBO_POS_ACTION=none ;;
    'tags:assign:1') _SCIEBO_POS_ACTION=none ;;
    'tags:clear:0') _SCIEBO_POS_ACTION=none ;;
    'hydrate:-:0') _SCIEBO_POS_ACTION=none ;;
    'logs:show:0') _SCIEBO_POS_ACTION=none ;;
    'logs:tail:0') _SCIEBO_POS_ACTION=none ;;
    'logs:path:0') _SCIEBO_POS_ACTION=none ;;
    'edit:-:0') _SCIEBO_POS_ACTION=none ;;
    'ignored:-:0') _SCIEBO_POS_ACTION=none ;;
    'preview:-:0') _SCIEBO_POS_ACTION=none ;;
    'download:-:0') _SCIEBO_POS_ACTION=none ;;
    'download:-:1') _SCIEBO_POS_ACTION=none ;;
    'help:-:0') _SCIEBO_POS_ACTION=commands ;;
  esac
  if [ -z "$_SCIEBO_POS_ACTION" ]; then
    case "$cmd:$sub" in
    'trash:restore') _SCIEBO_POS_ACTION=none ;;    'trash:rm') _SCIEBO_POS_ACTION=none ;;    esac
  fi
}

_sciebo() {
  local cur cmd='' sub='-' w i pos=0 pending_flag='' is_dispatch=0 seen_sub=0
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"

  # --help/-h before the cursor ends completion.
  for ((i = 1; i < COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in
      -h | --help) return 0 ;;
    esac
  done

  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${COMP_WORDS[i]}"
    if [[ -n "$pending_flag" ]]; then
      pending_flag=''
      continue
    fi
    case "$w" in
      --*=*) continue ;;
      -*)
        _sciebo_opt_lookup "${cmd:--}" "$sub" "$w"
        case "$_SCIEBO_OPT_KIND" in
          value | optional-value | repeatable | two-arg) pending_flag="$w" ;;
        esac
        continue
        ;;
    esac
    if [[ -z "$cmd" ]]; then
      cmd="$w"
      if _sciebo_is_dispatch "$cmd"; then is_dispatch=1; else is_dispatch=0; fi
    elif [[ "$is_dispatch" -eq 1 && "$seen_sub" -eq 0 ]]; then
      sub="$w"
      seen_sub=1
    else
      pos=$((pos + 1))
    fi
  done

  # A "--flag=partial" at the cursor completes that flag's value inline,
  # for every valued option (not just a hardcoded pair).
  case "$cur" in
    --*=*)
      local flagname="${cur%%=*}" partial="${cur#*=}"
      _sciebo_opt_lookup "${cmd:--}" "$sub" "$flagname"
      case "$_SCIEBO_OPT_KIND" in
        value | optional-value | repeatable | two-arg)
          _sciebo_complete_action "$_SCIEBO_OPT_ACTION" "$partial"
          local j
          for j in "${!COMPREPLY[@]}"; do
            COMPREPLY[j]="${flagname}=${COMPREPLY[j]}"
          done
          ;;
      esac
      return 0
      ;;
  esac

  if [[ -n "$pending_flag" ]]; then
    _sciebo_opt_lookup "${cmd:--}" "$sub" "$pending_flag"
    # An optional-value option whose next word looks like a flag is not
    # given a value by the real parser (it falls back to its default and
    # the word is a fresh option instead); every other kind always
    # consumes the next word, matching opt_parse.
    if [[ "$_SCIEBO_OPT_KIND" != optional-value || "$cur" != -* ]]; then
      _sciebo_complete_action "$_SCIEBO_OPT_ACTION" "$cur"
      return 0
    fi
  fi

  if [[ -z "$cmd" ]]; then
    _sciebo_compgen "$cur" "$_sciebo_commands $_sciebo_global_opts"
    return 0
  fi

  if [[ "$cur" == -* ]]; then
    _sciebo_compgen "$cur" "$(_sciebo_options_for "$cmd" "$sub") $_sciebo_global_opts"
    return 0
  fi

  if [[ "$is_dispatch" -eq 1 && "$seen_sub" -eq 0 ]]; then
    _sciebo_compgen "$cur" "$(_sciebo_subs_for "$cmd")"
    return 0
  fi

  _sciebo_pos_action "$cmd" "$sub" "$pos"
  _sciebo_complete_action "$_SCIEBO_POS_ACTION" "$cur"
}

complete -F _sciebo sciebo
